### ISSUE TITLE
Import first version of blockchain types from `cardano-sl`

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#1]
The new implementation needs to be able to deserialise exisiting blockchains and serialise to the same format until a hard-fork is taken. The simplest way to ensure this is to import the types from the old blockchain along with their golden/round-trip tests. We can then modify and extend those types, ensuring that all tests pass and any new serialisation is done conditionally on the software version.

**Comment by dnadales** [comment]
Do we use github issues now instead of YouTrack, or are these kind of issues different in some way? Just curious :)

**Comment by mdimjasevic** [comment]
I've been wondering the same as @dnadales .

**Comment by ruhatch** [comment]
This is a bit coarse at the moment - I'm going to add separate issues for the sub-packages
