### ISSUE TITLE
Replace _txInputs of Tx with nonempty-containers Set in Shelley

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#111]
Right now we're using a non-empty list, but this should really be a set and makes interaction with `UTxO` neater

**Comment by ruhatch** [comment]
We should leave this for now I think. The `non-empty` library needs a bit of work before I would want to consider using it. The main issues are:

- No `Foldable` instances for `Data.NonEmpty.Set`
- Unclear type naming: all the types are named `T` for some reason. I believe this is so we could make our own aliases for anything isomorphic, but still slightly odd.
- Missing `Aeson` instances

We could contribute the missing instances and discuss naming with the library author, but that's a longer-term solution.

**Comment by dnadales** [comment]
Can't we just define something like `data NESet e = NESet e (Set e)` and add instances for it?

**Comment by ruhatch** [comment]
Yeah, we could do something like that, but I was hoping to have a library-based solution. We should still think about it though - maybe I'll reopen this.

**Comment by ruhatch** [comment]
After some investigation it turns out that we cannot use a set in the OBFT era and will have to wait for Shelley to make that change. The reason is to do with transaction witnesses and matching them to specific transaction inputs. In the old implementation a transaction contained a list of transactions inputs. Another datatype `TxAux` holds the transaction and a list of witnesses, one for each input. The only way to match these is the position in the list. If we turn the list of inputs into a set, we don't guarantee the same ordering, so finding the right witness becomes harder. We would have to try to verify against several witnesses until we found a matching one, which is wasteful.

Instead, we can wait until the Shelley implementaion to use a non-empty set.

**Comment by ruhatch** [comment]
In Shelley we'll be working from the executable spec, so we'll deal with this when translating from that
