### ISSUE TITLE
Generator framework for small-step-semantics

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#116]
How do we generate test data for a small-step-semantics system?

**Comment by commandodev** [comment]
@nc6 Do you still intend to break this down more? Or is it mostly complete with the goblins work? If so could you attach it to the PR in question and remove the `need-breakdown` label?

**Comment by nc6** [comment]
I've done some breakdown of this task:

* Generator framework for small-step semantics
** STS systems
*** Encode delegation
*** Encode updates
*** Tie blockchain layer to ledger layer
** Change `BreedingPit` to work with `ProgressiveGen`.
   At the moment, this requires a single generator for state, env and signal.
   But it would be nice to create a single env and state, and cycle through a
   few signals in order to get a stronger measure of score.
** ProgressiveGen for valid chains
   Can we make use of Damian's work to get composable (valid) generators?
*** Generator for valid ledger states
**** Generator for UTxO (plus witnessing)
     To what extent does this need to be different from what Matthias already
     has? Can we re-use this?
**** Generator for delegation
**** Generators for update states
*** Generator for valid chain states
** Invalid chains
*** Move Goblins to own package
*** Incorporate 'mutators' in some sensible fashion
*** Allow saving/restoring goblin populations from disk
*** Get goblins successfully generating all failure conditions
*** Failure case coverage
    How do we make sure we have good coverage over chains and failure cases?
    - Code coverage testing?
    - Duncan's idea of continually refining failure conditions.

I presume the idea is to create tasks only for the leaf nodes?

**Comment by dnadales** [comment]
Closing this as we already have some generators in place, which we're using to validate the actual code. Some questions remain unanswered, but we can add smaller issues later if needed.
