### ISSUE TITLE
Annotate types with validity state

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#130]
We have a number of types that want to preserve invariants. We can avoid constructing invalid instances of these types by hiding the constructors and only exposing safe constructors that we can test enforce the invariants. 

This works for most cases, but decoding from the binary format presents a couple of issues. Performing checks during decoding can be expensive and cause significant slow downs. In many cases the checks require external information not available during decoding anyway, so we have to construct unvalidated values in those cases.

So to get around this problem we want to encode the validity in the types. There are a couple of techniques for doing this. 

One is to add an `UnvalidatedFoo` `newtype`-wrapper around a `Foo`. We can then construct safe `Foo`s as normal, but not decode them. Instead we decode an `UnvalidatedFoo`, that we can only turn in to a `Foo` through the validation function `validateFoo :: UnvalidatedFoo -> Foo`.

The other is through a phantom type, so we change `Foo` to `Foo (v :: Validity)` for some kind `data Validity = Valid | Unvalidated`. This would allow us to write functions that are polymorphic over the validity state. We could also do `data FooV (v :: Validity) = ...` and `type Foo = FooV Valid`. So that all the existing references to `Foo` that we thread a `FooV Valid` to don't have to change at all, but are now safer.

Both of the depend on a splitting of the `Bi` class into `ToCBOR` and `FromCBOR`. We would want `ToCBOR Foo` and `FromCBOR UnvalidatedFoo`, in the first case, and `ToCBOR (Foo Valid)` and `FromCBOR (Foo Unvalidated)` in the second case.

**Comment by mdimjasevic** [comment]
This sounds like an interesting issue. I don't have enough domain knowledge to see why would you store some data in a type you want to have some properties, but to actually check these properties after already having data in this type. I'd be interested to chat about this to understand the issue at hand better.

**Comment by ruhatch** [comment]
Probably won't end up doing this for now

**Comment by dnadales** [comment]
But don't we want to do this at all?
