### ISSUE TITLE
Specify the block size

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-byron#137]
As Duncan said, now that we have the [| x |] serialised syntax, we can talk about sizes of blocks.

Add to the blockchain layer the specification for the block size. In particular, in validating the old blocks, we must apply different size limits for normal blocks vs epoch boundary blocks (EBBs). For normal blocks we use the limit that comes from the protocol parameter for that purpose. For EBBs we apply a fixed 2Mb limit.

**Comment by nc6** [comment]
Do we want this in the chain spec? This feels like something that should be in the consensus layer. cc @dcoutts

**Comment by mdimjasevic** [comment]
The PR #154 addressed this issue.
