### ISSUE TITLE
Give `SlotId` a more specific name, and `FlatSlotId` a better name.

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#170]
A slot-id could represent the absolute index of a slot across epochs, or the index of the slot within an epoch. To remove ambiguity regarding what `SlotId` means we should give it a more specific name. Furthermore, `FlatSlotId` should be given a better name. The formal specifications should be updated to reflect the new naming conventions.

## Proposed Solution

First we need to rename `SlotId` to something more appropriate, since it is now defined as:

```haskell
data SlotId = SlotId
  { siEpoch :: !EpochIndex
  , siSlot  :: !LocalSlotIndex
  } deriving (Show, Eq, Ord, Generic)
```

This data structure should be placed in a different module from `Cardano.Chain.Slotting.SlotId`, to reflect the fact that it is a legacy data structure, and we shouldn't use it in any new code.

Instead of `LocalSlotIndex` we can use something like `SlotCount`, which clearly reflects what this type denotes.

`FlatSlotId` should be renamed to `SlotNo` to be consistent with [`ouroboros-network`](https://github.com/input-output-hk/ouroboros-network/pull/374).

Then we need to make sure the `SlotId` is only used at the block header (since we cannot change the block structure that is already persisted), and use `SlotNo` everywhere else. This means that when we decode a block we need to translate the epoch-and-slot pair (represented by the `SlotId` data structure above), to a `SlotNo`, which in turn will require that we use a fixed number of slots-per-epoch.

By hard-coding the number of slots per epoch we won't be able to use a smaller number in the tests, so we could add a new protocol parameter, with a default value.

Additionally, for the sake of consistency, `EpochIndex` should be renamed to `EpochNo`.

## Next Actions

- [ ] Identify all the places in which a translation from `SlotId` to `FlatSlotId` is needed, so that the use of `SlotId` can be restricted to the block serialization and de-serialization. Note that we use old names here since renaming will/should take place at a later stage.
- [ ] Bump the version of `cardano-ledger-specs`.
- [ ] Rename `SlotId` to `EpochAndSlotCount`, and place it in a module that reflects the fact that it should be used in new code. Use `SlotCount` instead of `LocalSlotIndex`.
- [ ] Rename `EpochIndex` to `EpochNo`.
- [ ] Rename `FlatSlotId` to `SlotNo`.
- [ ] Add a protocol parameter for the number of slots per epoch, so that this can be tweaked in tests. This protocol parameter should have a default value, since it won't be present in the Byron era.

## Additional actions

- [x] Check whether the undo log is still needed (see `Cardano.Chain.Block.SlogUndo`).

**Comment by dnadales** [comment]
@dcoutts suggested:

>  "slot number" should be the time slot index from genesis, and where we need epoch + index within epoch, we should use a different name.

**Comment by dnadales** [comment]
It seems we cannot get rid of `SlotId` in `ToSign`, since values of this type were signed in the existing chain already:

```haskell
-- | Data to be signed in 'Block'
data ToSign = ToSign
  { _msHeaderHash  :: !HeaderHash
  -- ^ Hash of previous header in the chain
  , _msBodyProof   :: !Proof
  , _msSlot        :: !SlotId
  , _msChainDiff   :: !ChainDifficulty
  , _msExtraHeader :: !ExtraHeaderData
  } deriving (Eq, Show, Generic)

```

**Comment by erikd** [comment]
That means we need to keep something that is iomorphic with `SlotId`.

**Comment by dnadales** [comment]
> Add a protocol parameter for the number of slots per epoch, so that this can be tweaked in tests. This protocol parameter should have a default value, since it won't be present in the Byron era.

I don't think we can do this when encoding and decoding data: 

```haskell
class Typeable a => Bi a where
  encode :: a -> E.Encoding

instance Bi ConsensusData where
  encode cd = ...
```

**Comment by avieth** [comment]
> > Add a protocol parameter for the number of slots per epoch, so that this can be tweaked in tests. This protocol parameter should have a default value, since it won't be present in the Byron era.
> 
> I don't think we can do this when encoding and decoding data:

Number of slots per epoch is determined by the `k` parameter, no? We can already reconfigure that.

What does this have to do with encoding/decoding?

**Comment by erikd** [comment]
Theoretically `k` can be configured and in fact the mainet and the testnets use different values for `k`, but for the mainnet, `k` has only ever been a single value, `2160`.

**Comment by dnadales** [comment]
> Number of slots per epoch is determined by the k parameter, no? We can already reconfigure that.

Yes. Now the question is whether this relation between `k` and the number of slots per epoch will always remain the same.

> What does this have to do with encoding/decoding?

Let's see if I got this right: right now the blocks are stored on disc using a `(EpochIndex, LocalSlotId)` pair to refer to a particular absolute slot. If we want to decode this into an absolute slot number, called `SlotNo` everywhere else, we need to know how many slots per epoch are there (furthermore, we need to assume that this number was always constant across epochs). Does this make sense or am I missing something @avieth ?

**Comment by avieth** [comment]
>  Let's see if I got this right: right now the blocks are stored on disc using a (EpochIndex, LocalSlotId) pair to refer to a particular absolute slot. If we want to decode this into an absolute slot number, called SlotNo everywhere else, we need to know how many slots per epoch are there (furthermore, we need to assume that this number was always constant across epochs). Does this make sense or am I missing something @avieth ?

Sure, but this can be done in 2 steps: decode the pair, then convert to a `SlotNo` using a function that takes the slots-per-epoch as a parameter. I don't think the entire conversion needs to go into a `Bi` instance.

**Comment by ruhatch** [comment]
> Sure, but this can be done in 2 steps: decode the pair, then convert to a SlotNo using a function that takes the slots-per-epoch as a parameter. I don't think the entire conversion needs to go into a Bi instance.

If you do it this way then how do you decode a larger type, such as Header, that contains a SlotId now, but we want to contain a SlotNo?

**Comment by mhuesch** [comment]
> This data structure should be placed in a different module from Cardano.Chain.Slotting.SlotId, to reflect the fact that it is a legacy data structure, and we shouldn't use it in any new code.

Suggestion: we could remove `Cardano.Chain.Slotting.SlotId` from the `Cardano.Chain.Slotting` export-all list, so that it has to be explicitly imported. This would, hopefully, convey what Damian says in the quote.
