### ISSUE TITLE
Add cardano-binary package

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#18]
This is an import and clean up of the `cardano-sl-binary` package in the legacy codebase. The template haskell code should be removed, as it is better to have hand-written instances for that kind of thing, and TH makes cross-compilation more tricky.

**Comment by neongreen** [comment]
> as it is better to have hand-written instances for that kind of thing

Well, this is rather questionable. TH was introduced exactly to avoid hard-to-avoid bugs that can occur with hand-written instances.

**Comment by ruhatch** [comment]
Hi @neongreen!

I agree, in many cases using TH or Generics would decrease the likelihood of bugs, and as an added bonus reduce the amount of code. In this specific case, with a binary serialisation format that might be subject to modification, being explicit means we can add backwards compatibility code to a specific instance or, if something goes wrong, the faulty code is right there for us to see. Also a newcomer to the code will be able to see how something is encoded/decoded without having to `-ddump-splices`. We do have to be more careful, but this is the code where we'd rather be explicit and careful.
