### ISSUE TITLE
Change PublicKey and SecretKey to VerificationKey and SigningKey

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#181]
We currently have a bunch of keys that are named Public and Secret, but are used only for signature schemes. We can therefore rename them to Verification and Signing, to capture their semantic content.

**Comment by ruhatch** [comment]
@erikd this isn't done yet! Any reason for closing?

**Comment by erikd** [comment]
I thought that commit was the fix. Reopenning.
