### ISSUE TITLE
Generator for (valid) delegation

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#194]
Add generators for delegation transition rules. 

Remaining tasks:

- [x] Add parameters to control the size of the traces. Try to leverage on `hedgehog`'s `Gen` parameters.
- [x] Write property based tests for the `DELEG` traces.
- [x] Add RTS constraints to the tests.
- [x] Organize the code.
- [x] Factor out possible duplication.
- [ ] OPTIONAL: consider adding [coverage information](https://hackage.haskell.org/package/tasty-hedgehog-coverage-0.1.0.0/docs/Test-Tasty-Hedgehog-Coverage.html)
- [x] Apply hlint.
- [x] Remove warnings.
- [x] Update the README if necessary.
- [x] Rebase from `master`.

# Retrospective

See the comments in this issue! Also:

- A lot of time spent in trying to make `nix` build with the `capability` package. At this package was not necessary, since I did not use `ProgressiveGen`.
- Had to add ad-hoc tests for the STS rules (as a way of some basic sanity check).
- Had to add property based tests for the `DELEG`.
- Tests detected errors in the Haskell translation of the STS rules for delegation, which is nice. However this takes additional time, which we should take into consideration when estimating tasks related to coding STS in Haskell or their generators.
- I could not make `ProgressiveGen` work. Tried several approaches. Had lengthy (but quite insightful) discussions with @nc6. At the end we settle for the "generate-then-validate" approach, in which we would generate signals and then validate them using the STS rules (hoping that the signal generators won't need much knowledge of the rules).
- :clock1: Had to spend quite some time trying learn how to use `ghcid` and `nix` in a workflow that resembles the one I was used to with `stack`. I'm still unsatisfied by the results.
- I spent a lot of time hammering on the `GenM` monad: shuffling the monad transformers stack, adding auxiliary functions, etc. At the end this monad was removed, so a lot of wasted effort here as well.
- Trying to workaround the [limitations in `ghci`](https://github.com/haskell/cabal/issues/5103) (see also [this issue](https://github.com/haskell/cabal/issues/5374)) is not worth the time,  specially since a `stack` workflow could be implemented. Additionally, by explaining the workaround in the README will probably take a lot of effort.

Things that we need to address:

- Classify the test cases: how do we know that we're covering all the interesting delegation cases?

**Comment by dnadales** [comment]
Consider this encoding of the `SDELEG` rule, in which I intentionally introduced an error:

```haskell
instance STS SDELEG where
  ...
  transitionRules =
    [ do
        TRC (env, st, cert) <- judgmentContext
        verify cert ?! DoesNotVerify
        notAlreadyDelegated st cert ?! HasAlreadyDelegated
        notAlreadyScheduled env st cert ?! IsAlreadyScheduled
        Set.member (cert ^. dwho . _1) (env ^. allowedDelegators) ?! IsNotGenesisKey
        env ^. epoch <= cert ^. depoch ?! IsPastEpoch
        return $ st
          & scheduledDelegations <>~ [((env ^. slot) `addSlot` (env ^. liveness)
                                      , cert ^. dwho
                                      )]
          & keyEpochDelegations %~ Set.insert (env ^. epoch, cert ^. dwho . _1)
    ]
    where
      verify :: DCert -> Bool
      verify = const True
      -- Check that this delegator hasn't already delegated this epoch
      notAlreadyDelegated :: DSState -> DCert -> Bool
      notAlreadyDelegated st cert =
        Set.notMember (cert ^. depoch, cert ^. dwho . _1) (st ^. keyEpochDelegations)
      -- Check whether there is a scheduled delegation from this key
      notAlreadyScheduled :: DSEnv -> DSState -> DCert -> Bool
      notAlreadyScheduled env st cert =
        -- TODO: find out why flipping this doesn't break the tests!
        -- TODO: should be 'List.notElem'
        List.elem
          ((env ^. slot) `addSlot` (env ^. liveness), cert ^. dwho . _1)
          (st ^. scheduledDelegations . to (fmap $ fmap fst))
```

Flipping the condition from `List.notElem` to `List.elem` make the tests up to commit 2a45a9b49fbbc2b4af550b4b6b85d14300887c58 pass. The problem here seems to be that encoding the property wrongly, will result in a generator that produces empty traces only, e.g.:

```haskell
Trace
  { _traceEnv =
      DSEnv
        { _dSEnvAllowedDelegators =
            fromList
              [ VKeyGen (VKey (Owner 0))
              , VKeyGen (VKey (Owner 1))
              , VKeyGen (VKey (Owner 2))
              , VKeyGen (VKey (Owner 3))
              , VKeyGen (VKey (Owner 4))
              , VKeyGen (VKey (Owner 5))
              , VKeyGen (VKey (Owner 6))
              ]
        , _dSEnvEpoch = Epoch 0
        , _dSEnvSlot = Slot 0
        , _dSEnvLiveness = SlotCount 1
        }
  , _traceInitState =
      DIState
        { _dIStateDelegationMap = fromList []
        , _dIStateLastDelegation = fromList []
        , _dIStateScheduledDelegations = []
        , _dIStateKeyEpochDelegations = fromList []
        }
  , _traceTrans =
      [ ( DIState
            { _dIStateDelegationMap = fromList []
            , _dIStateLastDelegation = fromList []
            , _dIStateScheduledDelegations = []
            , _dIStateKeyEpochDelegations = fromList []
            }
        , [])
      , ( DIState
            { _dIStateDelegationMap = fromList []
            , _dIStateLastDelegation = fromList []
            , _dIStateScheduledDelegations = []
            , _dIStateKeyEpochDelegations = fromList []
            }
        , [])
      , ( DIState
            { _dIStateDelegationMap = fromList []
            , _dIStateLastDelegation = fromList []
            , _dIStateScheduledDelegations = []
            , _dIStateKeyEpochDelegations = fromList []
            }
        , [])
      ]
  }
```

These empty trace will satisfy the `propDCertsAreTriggered` property, since triggering no certificates will result in an empty `dms` map, which coincides with the empty state in the trace above. So it seems we need some properties that state that generators should be able to produce "interesting" traces eventually.

**Comment by dnadales** [comment]
I coded the following property, which checks that if we attempt to reschedule a certificate it will be rejected.

```haskell
-- | We can generate traces with a non-empty final state.
rejectDupSchedDelegs :: Property
rejectDupSchedDelegs = property $ do
  (tr, dcert) <- forAll $ do
    tr <- trace @DELEG
          `suchThatLastState` (not . null . view scheduledDelegations)
    let vkS =
          case lastState tr ^. scheduledDelegations of
            (_, (vkS, _)):_ -> vkS
            _ -> error $  "This should not happen: "
                       ++ "tr is guaranteed to contain a non-empty sequence of scheduled delegations"
    vkD <- vkGen
    epo <- epochGen
    let dcert
          = DCert
          { _dbody = (vkD, epo)
          , _dwit = Sig vkS (owner vkS)
          , _dwho = (vkS, vkD)
          , _depoch = epo
          }
    return (tr, dcert)
  let pfs = case applySTS (TRC (tr ^. traceEnv, lastState tr, [dcert])) of
        Left pfs -> pfs
        Right _ -> []
  assert $ SDelegSFailure (SDelegFailure IsAlreadyScheduled) `elem` pfs
```

When the error shown in my previous comment is removed the property passes. However, when I re-introduce the error the heap is exhausted. So the property does not pass, which is what we want, but we do not get useful feedback as to why the property failed :/ Furthermore, it takes about half a minute to exhaust the heap.

**Comment by dnadales** [comment]
By increasing the heap limit, one would get the `Gave up` message from hedgehog, which doesn't hint much at the fact that it gave up when trying to produce a trace with a non-empty sequence of scheduled delegations. But it is better than nothing...
