### ISSUE TITLE
Generator for (valid) blockchain (delegation)

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#195]
Generator at the blockchain layer (when only carrying delegation payload).

Requires:

- [x] Compute the size of a block and block header.
- [x] Adapt the STS rules to match the modification in the spec in `master`.
- [x] Define the `HasTrace` instance for the `CHAIN` transition system.

Minor tasks before PR:

- [x] Add compiler warnings, treat warnings as errors, and `development` flag.

Retrospective
==========

- Nix build:
  - :disappointed: The addition of `cardano-prelude`, which was really easy with `stack`, broke the `nix` build, and I'm spending quite a lot of time trying to figure out how to fix this.
  - :disappointed: It is still not clear why [PR-246](https://github.com/input-output-hk/cardano-chain/pull/246#issuecomment-456783393), which will automate this painful process, hasn't been merged.
  - :pray: devops (@cleverca22) was really helpful.
  - :scream: editing the nix configuration feels like black magic to me.

**Comment by nc6** [comment]
Depends on #194

**Comment by dnadales** [comment]
Depends on #278.

**Comment by dnadales** [comment]
Closed by https://github.com/input-output-hk/cardano-chain/pull/301
