### ISSUE TITLE
Add a `Cardano.Prelude`

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#2]
In the legacy codebase we were using the `Universum` prelude. For a large project like this it makes sense to have a `Cardano.Prelude`. While importing code from the old codebase this can simply re-export `Universum`, but we can then easily replace this when we want.

**Comment by dnadales** [comment]
I'd be in favor of the smallest functional prelude we can find.

**Comment by ruhatch** [comment]
Closing and opening a new issue for replacing `Universum`
