### ISSUE TITLE
Add RTS options to the tests to limit memory usage

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#213]
We have a situation in which tests consume all available memory. To detect this we should add RTS options that limit memory usage.

**Comment by ruhatch** [comment]
Approach described in [this blog post](http://neilmitchell.blogspot.com/2015/09/detecting-space-leaks.html)

**Comment by dnadales** [comment]
Could this be as simple as [what I did here](https://github.com/input-output-hk/cardano-ledger-specs/blob/ed8424e9a85b9a3be44bb72e69a404426c7e334f/byron/ledger/executable-spec/cs-ledger.cabal#L107)?

(This is also a way of having people check that I didn't do something stupid)
