### ISSUE TITLE
Do not re-export everything?

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#220]
When I'm looking up definitions I usually go to the imports section, for instance:

```haskell
import Cardano.Chain.Common ( ... foo ...)
```

But then when I go to the Cardano.Chain.Common module I find this pattern, which we use a lot:

```haskell
module Cardano.Chain.Common
  ( module X
  )
where

import Cardano.Chain.Common.AddrAttributes as X
import Cardano.Chain.Common.Address as X
import Cardano.Chain.Common.AddressHash as X
import Cardano.Chain.Common.AddrSpendingData as X
import Cardano.Chain.Common.AddrStakeDistribution as X
import Cardano.Chain.Common.Attributes as X
import Cardano.Chain.Common.BlockCount as X
import Cardano.Chain.Common.ChainDifficulty as X
import Cardano.Chain.Common.Lovelace as X
import Cardano.Chain.Common.LovelacePortion as X
import Cardano.Chain.Common.Merkle as X
import Cardano.Chain.Common.Script as X
import Cardano.Chain.Common.StakeholderId as X
import Cardano.Chain.Common.TxFeePolicy as X
import Cardano.Chain.Common.TxSizeLinear as X
```

Now the problem comes when looking for `foo`, which is imported from Cardano.Chain.Common: where does `foo` come from? We can resort to tools like (git) `grep` and `silversearcher-ag` but they will give too many `foo` matches. Gnu-tags sometimes helps but it has its limitations (for instance if we reexport a function from some other library).

Is this "re-export" pattern needed? Or could we write re-exports like this:

```haskell

￼module Foo
  ( module Bar
  , ...
  )
where

import Bar (func0, func1, ...)
```

Which takes more time to write, but it helps in tracing where each symbol came from.

**Comment by mdimjasevic** [comment]
I'm in favor of explicit imports too. We don't import 100 of definitions from a single sub-module. If we do, then that's an indicator that the module might need to be reorganised.

**Comment by redxaxder** [comment]
How many `foo` matches are you getting from `ag` or `git grep`?

We're considering shifting a burden from this searching task to a code-changing task, so it would be good to be able to compare their respective sizes.

The other burden is an additional file changed whenever a symbol is added/removed/renamed from one of the submodules, which hits me pretty often during a refactor.

**Comment by dnadales** [comment]
> How many foo matches are you getting from ag or git grep?

I assume the question is rhetorical :)

 > We're considering shifting a burden from this searching task to a code-changing task, so it would be good to be able to compare their respective sizes.

True. But we have to factor in how many time people will read the code. We also use explicit imports for this reason (and having this re-exporting pattern defeats its purpose).

> The other burden is an additional file changed whenever a symbol is added/removed/renamed from one of the submodules, which hits me pretty often during a refactor.

Don't we have the same problem when using explicit exports and imports?

All in all, I want to avoid bikesheding, so if most people think this re-exporting pattern in fine, please feel free to close this.

**Comment by erikd** [comment]
@dnadales if you are looking for the definition of `foo`, you should be searching for `^foo` (`foo` occurring only at the start of a line), like `grep -r ^foo .`

**Comment by ruhatch** [comment]
I don't think we'll be doing this in the current codebase, so I'll close this for now
