### ISSUE TITLE
Support epoch boundary blocks in the blockchain specification

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-byron#225]
In its current version, the blockchain specification (both LaTeX and Haskell parts) doesn't support epoch boundary blocks. As @nc6 pointed out, Figure 6 (the blockchain extension rule) allows extension by real blocks only, and not by epoch boundary blocks. Support for epoch boundary blocks is needed to validate Byron release chains.

Support for epoch boundary blocks in the blockchain specification of the Byron release needs to be added.

**Comment by mdimjasevic** [comment]
@nc6, I forgot about this in the meantime, but what are called non-genesis blocks in the blockchain specification of the Byron release and the transition to Shelley already do contain a flag indicating if they're epoch boundary blocks (see Section 3.3 of the LaTeX specification). Therefore, I'd say that a type for epoch boundary blocks is not missing. Rather, what is needed are more specific preconditions on transitions in inference rules. Do you agree?

**Comment by nc6** [comment]
Addressed by #239
