### ISSUE TITLE
Define GHC version in a single place for the nix build

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#227]
The nix build is currently setup to use GHC 8.6.1, which has some major bugs in it. We could move it to 8.6.3, but currently that requires changes in a few places. We should have this defined centrally.

**Comment by dnadales** [comment]
Didn't we fix this already?

**Comment by ruhatch** [comment]
Nix building is now done by `nix-tools`, which will generate a file with the GHC version from our stack snapshot. So an update of GHC should be as simple as:
1. Updating `snapshot.yaml` in `cardano-prelude`
2. Updating `stack.yaml` `resolver`s in `cardano-ledger`
3. Running `scripts/nix-tools-generate.sh`

**Comment by ruhatch** [comment]
This may require updating the version of `iohk-nix` if the compiler version you're switching to isn't supported in the current version of `iohk-nix`.
