### ISSUE TITLE
Integrate executable ledger spec into consensus layer

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#240]
This covers the first integration point between the consensus layer and the ledger layer.

The consensus layer expects a function which takes a block and an existing chain and attempts to produce a new chain. We should be able to instantiate this with the executable chain spec. It may currently require us to ignore some parts of chain validation which are not implemented (e.g. updates) and we may need to implement a few more things on the chain level (e.g. epoch transitions).

**Comment by mdimjasevic** [comment]
I'm putting this one on hold until I implement https://github.com/input-output-hk/ouroboros-network/issues/168.

**Comment by mdimjasevic** [comment]
Closing in favor of https://github.com/input-output-hk/fm-ledger-rules/issues/241.
