### ISSUE TITLE
Typo in in "Domain and range operations on sequences"?

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#241]
I was just going through old notes from Berlin...

Should `$A \restrictdom R$` instead be `$S \restrictdom R$` [here](https://github.com/input-output-hk/cardano-chain/blob/3bf95f74d459226df4c72db0b0a693eebe6739aa/specs/ledger/latex/notation.tex#L41)?

**Comment by mhuesch** [comment]
@dnadales I'm not sure if there are notifications for new issues, so tagging you just to be safe.

**Comment by dnadales** [comment]
> Should $A \restrictdom R$ instead be $S \restrictdom R$ here?

Yes! Thank you! I just updated this in my current branch. I'll submit a PR soon.


> @dnadales I'm not sure if there are notifications for new issues, so tagging you just to be safe.

I'm subscribed to all the notification in this repo, so I got a notification for this, but thanks for double checking :)

**Comment by mhuesch** [comment]
Great - you're welcome!
