### ISSUE TITLE
Federate protocol parameters in the ledger spec

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#253]
Currently the set of required protocol parameters for the ledger spec is defined in the "Update" section. In the chain spec I have introduced "federated" protocol parameters which are defined alongside the relevant system, along with the type of the value.

This issue would cover:
- Introducing the (slight abuse of) notation used to define these.
- Moving the ledger spec parameters to the relevant places.

**Comment by nc6** [comment]
cc @dnadales

**Comment by dnadales** [comment]
I can help with this, but I'm not sure what do we want :) 

> Moving the ledger spec parameters to the relevant places.

Is the idea to distribute the definition of the protocol parameters to the places where they are needed?

**Comment by dnadales** [comment]
Moved to https://github.com/input-output-hk/fm-ledger-rules/issues/344
