### ISSUE TITLE
Model explicit absolute/relative slot calculations

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#255]
As per https://input-output-rnd.slack.com/archives/CCZSDE005/p1548153284081900:

- When we switch from BFT to Praos, we will need to change the number of slots per epoch. Currently this is hard-coded. We also intend to switch from using relative "epoch, slot" pairs to using absolute slots. As such, we should explicitly model the calculations involved in translating between these two concepts under the assumption of a configurable number of slots per epoch.

**Comment by nc6** [comment]
For the consensus layer, it would also be helpful if the ledger layer kept track of the length of historical epochs.

**Comment by dnadales** [comment]
More requirements gathered from slack: I don't know whether you want to add them to the issue description @nc6 or add them as a separate issue:

- The size of an epoch should be in a map of a type like `:: Map EpochIndex EpochSize`.
- When we store blocks in the immutable store (the part of the chain that we are sure will not be rolled back), we store them per epoch. when opening the DB we want a map of precisely this form, for all epochs up to including the current one, and each time that a new epoch is started, we must be told its size
