### ISSUE TITLE
Restrict delegation rules so that there is an isomorphism between genesis keys and delegators

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#257]
Having multiple keys delegating to the same key can open up the possibility for an attack in the OBFT era: if a malicious node, with key `vk_m` gets control of a key that issued the maximum number of allowed blocks in a given window `w`, then it can prevent a node holding a key `vk` from issuing a block by simply delegating to `vk`. In such case, the current rules will count the block as being issued by all the delegators `vk`, and since `vk_m` cannot issue any more blocks, `vk` will be prevented from issuing a block.

To prevent this situation, we could strengthen the pre-conditions of the delegation rules, so that there is an isomorphism between the genesis keys and their delegates. In other words, each genesis key most delegate to exactly one key (which might be the genesis key itself).

As an added advantage of this restriction, counting the keys that signed blocks become much simpler.

**Comment by kantp** [comment]
That sounds like a really good idea to me.

We should only make sure that devops is aware of this restriction, and does not get blindsided.

**Comment by disassembler** [comment]
We have 1:1 Genesis: delegation keys now so I don't see this being a problem.
