### ISSUE TITLE
Switch to new notation for assignment/equality

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#259]
Per the results of [this poll](https://input-output-rnd.slack.com/archives/CCZSDE005/p1548167327100200) we should switch to using `:=` for assignment (let-binding) in rules, and `=` for equality testing.

The following can be used to get a nicely-formatted `:=` in LaTeX

```
\newcommand{\leteq}{\ensuremath{\mathrel{\mathop:}=}}
```

**Comment by nc6** [comment]
Addressed in the chain spec

**Comment by dnadales** [comment]
Moved to: https://github.com/input-output-hk/fm-ledger-rules/issues/296
