### ISSUE TITLE
Include coverage information on CI

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#262]
It will be good to keep an eye on our test coverage. See https://github.com/input-output-hk/cardano-shell for inspiration.

**Comment by ksaric** [comment]
You can see the PR here - https://github.com/input-output-hk/cardano-shell/pull/37/files

After creating a repo on Coveralls, you need to copy the relevant code from `shell.nix` and copy the whole file `stack-hpc-coveralls.nix`, add COVERALLS_REPO_TOKEN in the environment of BuildKite.
That should be it.
