### ISSUE TITLE
Protocol version for the next epoch must be exposed before the end of the epoch

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#295]
When we learn the parameters/protocol version which will be alive for the next epoch (for epoch length knowledge), this should be made available to the consensus layer as soon as possible (rather than waiting for the new epoch).

**Comment by nc6** [comment]
Hold off on this for the moment, we might want to discuss this. Alternative is to expose the epoch transition directly, so the consensus layer can force it.

**Comment by dnadales** [comment]
Does the `fads` sequence in the blockchain interface state solves this? See
https://github.com/input-output-hk/cardano-chain/pull/300

**Comment by dnadales** [comment]
@nc6 ? :arrow_up: ?

**Comment by dnadales** [comment]
Moved to https://github.com/input-output-hk/fm-ledger-rules/issues/342
