### ISSUE TITLE
Split block header processing into protocol and payload components

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#305]
The current BHEAD rule includes things that pertain both to the protocol (such as signature counting) and to the payload (the Byron era ledger, such as verifying the maximum size and computing whether we are in a new epoch). For the purposes of integration with the consensus layer, it would be helpful to differentiate between these parts.

**Comment by mdimjasevic** [comment]
@nc6, is this ready to be closed?

**Comment by dnadales** [comment]
Moved to https://github.com/input-output-hk/fm-ledger-rules/issues/341
