### ISSUE TITLE
Missing initial rules in the new blockchain specification version

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-byron#306]
The new rules for blockchain (see in [Cardano.Spec.Chain.STS.Rule](https://github.com/input-output-hk/cardano-chain/tree/master/specs/chain/hs/src/Cardano/Spec/Chain/STS/Rule)) are missing initial rules. With that in mind, how to run the main `CHAIN` state transition system? Are there tests that execute it?

**Comment by dnadales** [comment]
The `CHAIN` transition system [has an initial rule](https://github.com/input-output-hk/cardano-chain/blob/master/specs/chain/hs/src/Cardano/Spec/Chain/STS/Rule/Chain.hs#L59). We can add initial rules for the other transition systems on a on-demand basis. I guess once #305 is implemented we will need them for the sub-transition systems we want to expose.

**Comment by dnadales** [comment]
Or were you referring to the latex spec?

**Comment by mdimjasevic** [comment]
Given that one version of the specification should mirror the other, I'm referring to both specifications.

**Comment by mdimjasevic** [comment]
Closing in favor of https://github.com/input-output-hk/fm-ledger-rules/issues/240.
