### ISSUE TITLE
Haddocks for cardano chain cannot be produced 

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#312]
We should remove the haddock errors (that might have carried over). Otherwise we cannot produce haddock documentation, and therefore we cannot use `hoogle`.

```
    src/Cardano/Chain/Update/Vote.hs:307:7: error:
        parse error on input ‘-- ^ This byte is part of the signed payload, but is not part of the transmitted payload.
          -- This is an implementation artifact of the previous’
        |
    307 |       -- ^ This byte is part of the signed payload, but is not part of the transmitted payload.
        |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by dnadales** [comment]
Maybe we need to check the haddock sanity in CI as well :man_shrugging:

**Comment by mhuesch** [comment]
The ability to use local hoogle was something I wanted in `cardano-sl` but the amount of work required seemed too great. Would love to see this set right in `cardano-chain` ❤️
