### ISSUE TITLE
Rename `ProxySecretKey`

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#321]
[`ProxySecretKey`](https://github.com/input-output-hk/cardano-chain/blob/3b2282983c993c450a8a57db3a136015a3003931/crypto/src/Cardano/Crypto/Signing/Proxy/SecretKey.hs#L64) appears to have migrated from `cardano-sl` to `cardano-chain`. It recently came to @intricate and my attention that this name is misleading, because the datatype doesn't contain any "secret" information (no secret keys or similar).

Doing a little digging just now, I found [a document](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/block-processing/types.md#proxy-key) which admits the name is a misnomer. Git blame [here](https://github.com/input-output-hk/cardano-sl/blame/develop/docs/block-processing/types.md#L1011) - this seems to have been known since 2018-01-11.

I'm not sure what a good replacement name would be. Perhaps something like `ProxyCertKey`?

**Comment by intricate** [comment]
Maybe `ProxyPublicKey`, even?

**Comment by mhuesch** [comment]
> Maybe `ProxyPublicKey`, even?

Yeah that would be good. Quote from the document says that, basically:

> Note that “proxy secret key” is a misnomer – it really is a public key, not a secret key.

**Comment by dnadales** [comment]
At some point we talked about using verification and signing key. CC: @ruhatch

**Comment by ruhatch** [comment]
Yeah, @dnadales is correct. We should be referring to these things by their function, not their privacy status! I would go with `ProxySigningKey`, and we will also move `SecretKey` to `SigningKey` and `PublicKey` to `VerificationKey`. See #181.

**Comment by mhuesch** [comment]
@ruhatch @dnadales: Agree that it would be good to switch from public/private to verification/signing in this context! In this specific case, though, we are talking about an orthogonal switch - about something named "private" which should be named "public" (or analogously something named "signing" which should be named "verification"). That is, moving down in this diagram:

```
private <-------> signing
   |                 |
public  <-------> verification
```

@intricate and I think that `ProxySecretKey` is backward in the up-downs dimension. It is called "Secret" but has no secret context. Or analogously, if we applied the #181 transformation (move L to R in above diagram) it would be called "Signing" but would actually do "Verification".

Seems that what is currently called `ProxySecretKey` might be most aptly named `ProxyVerificationKey`.

**Comment by dnadales** [comment]
> In this specific case, though, we are talking about an orthogonal switch - about something named "private" which should be named "public" (or analogously something named "signing" which should be named "verification"). 

Oh, sorry if I caused some confusion :grin:
