### ISSUE TITLE
Implement property tests for `Cardano.Chain.Txp.Validation` module

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-ledger-byron#323]
We currently have no property tests for the functions related to `Tx`.

**Comment by dnadales** [comment]
Bear in mind that we want to test this using transactions generated from our formal specs. [This in progress-PR](https://github.com/input-output-hk/cardano-chain/pull/308/commits/b08051be6891163399441ed8e5a55d2088f71a1f) tries to do this for the delegation mechanism `Cardano.Chain.Delegation.Validation`. 

I don't know whether you have other tests in mind.

**Comment by Jimbo4350** [comment]
Closed for now, will re-open (if needed) after Quickcheck training in April.
