### ISSUE TITLE
Concretise the type inside the `GenesisHash` newtype wrapper

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#332]
## Background

`GenesisHash` is defined as

```
newtype GenesisHash = GenesisHash { getGenesisHash :: forall a . Hash a }
```

To construct a value of this type one must use `coerce` from `Data.Coerce`. There's no obvious justification for this complicated approach.

## Proposed Solution

A `GenesisHash` should really be a hash of the bytes of the genesis configuration data. This is what we refer to as the genesis block. We use the type `Raw` to represent `ByteString`s that shouldn't be serialised before `hash`ing, so we should simply change the definition to use a `Hash Raw`.

**Comment by ruhatch** [comment]
## Next Action

- [ ] Replace `forall a . Hash a` with `Hash Raw` and fix up resulting type errors

**Comment by dnadales** [comment]
> ￼ Replace `forall a . Hash a` with `Hash Raw` and fix up resulting type errors

I tried that, but that results in a type mismatch here:

```
    /home/damian/github/input-output-hk/cardano-chain/src/Cardano/Chain/Block/Header.hs:203:46: error:
        • Couldn't match type ‘cardano-binary-1.5.0:Cardano.Binary.Class.Primitive.Raw’
                         with ‘AHeader ()’
          Expected type: HeaderHash
            Actual type: Hash
                           cardano-binary-1.5.0:Cardano.Binary.Class.Primitive.Raw
        • In the second argument of ‘mkHeaderExplicit’, namely ‘prevHash’
          In the expression: mkHeaderExplicit pm prevHash difficulty
          In an equation for ‘mkHeader’:
              mkHeader pm prevHeader
                = mkHeaderExplicit pm prevHash difficulty
                where
                    prevHash = either unGenesisHash hashHeader prevHeader
                    difficulty
                      = either
                          (const 0)
                          (succ . consensusDifficulty . headerConsensusData)
                          prevHeader
        |
    203 | mkHeader pm prevHeader = mkHeaderExplicit pm prevHash difficulty
        |                                              ^^^^^^^^
```
The problem is that `hashHeader :: Header -> HeaderHash`, where `type HeaderHash = Hash Header`, so we cannot make `Hash Raw` and `Hash Header` match. 

Shouldn't we change 

```haskell
newtype GenesisHash = GenesisHash { getGenesisHash :: forall a . Hash a }
```
to 

```
newtype GenesisHash = GenesisHash { getGenesisHash :: Hash Header }
```

I guess the problem might be that the genesis hash is not really the hash of a header :/

**Comment by dnadales** [comment]
> I guess the problem might be that the genesis hash is not really the hash of a header :/

If having 

```haskell
newtype GenesisHash = GenesisHash { getGenesisHash :: Hash Header }
```

is a valid option, the other questions is whether using

```haskell
unsafeAbstractHash :: HashAlgorithm algo => ByteString -> AbstractHash algo anything
```
when creating a hash from the genesis data would make sense.

**Comment by ruhatch** [comment]
Just chuck a `coerce` in there I'd say

**Comment by ruhatch** [comment]
I'd rather we're keeping track of what we get GenesisHash from and then mutate it at the usage site
