### ISSUE TITLE
The types in kEpochSlots are misleading

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#333]
The [`kEpochSlots`](https://github.com/input-output-hk/cardano-chain/blob/874275f0dd4b3505f63c6defb667cce649426887/src/Cardano/Chain/ProtocolConstants.hs#L28) function suggests that the number of slots in an epoch is computed from a number of blocks:

```
-- | Number of slots inside one epoch
kEpochSlots :: BlockCount -> SlotCount
kEpochSlots = fromIntegral . (*) 10 . getBlockCount
```

However the implicit assumption here is that the `BlockCount` is the chain security parameter.

We should remove this function, and calculate this inline, or create a function with more descriptive types.

**Comment by ruhatch** [comment]
I'm going to close this one for now
