### ISSUE TITLE
Select which test to run via command line arguments

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#336]
Currently there is no way to select which test to run:

```haskell
main :: IO ()
main = do
  opts <- execParser optsParser
  let scenario = optsTestScenario opts
  runTests
    [ Test.Cardano.Chain.Block.Bi.tests
    , Test.Cardano.Chain.Block.Validation.tests scenario
    , Test.Cardano.Chain.Common.Lovelace.tests
    , Test.Cardano.Chain.Delegation.Bi.tests
    , Test.Cardano.Chain.Epoch.File.tests
    , Test.Cardano.Chain.Genesis.Json.tests
    , Test.Cardano.Chain.Elaboration.Delegation.tests
    , Test.Cardano.Chain.Ssc.Bi.tests
    , Test.Cardano.Chain.Txp.Bi.tests
    , Test.Cardano.Chain.Txp.Json.tests
    , Test.Cardano.Chain.Txp.Validation.tests scenario
    , Test.Cardano.Chain.Update.Bi.tests
    , Test.Cardano.Chain.Update.Json.tests
    , Test.Cardano.Chain.Block.Validation.Spec.tests
    ]
```

It would be nice if we could select the test to run using `stack` in combination with `file-watch` and `ta` as follows:

```sh
stack test --file-watch --ta "-m *somePattern*"
```

There are options such as using `ghcid`, `ghci` or a combination of both however they have several shortcomings:

- No recompilation when `stack.yaml` or `*.cabal` files are changed
- No recompilation when local dependencies files are changed
- Colored output breaks in some cases

Also it might be nice to add a test framework, to avoid rolling our own.

**Comment by ruhatch** [comment]
We should be able to write a function that converts from a `hedgehog` `TestGroup` to a `testy-hedgehog` `TestTree`, which would then give us this functionality out of the box
