### ISSUE TITLE
Improve test failures

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-ledger-byron#338]
<h2> Background </h2>

@mhuesch raised a good point: https://github.com/input-output-hk/cardano-chain/pull/334#discussion_r258973970

<h2> Proposed Solution </h2>

Potentially one of [these](https://stackoverflow.com/questions/10112733/haskell-simple-constructor-comparison-function)

 (as pointed out by @mhuesch)

**Comment by mhuesch** [comment]
@Jimbo4350 Nice work on this.
