### ISSUE TITLE
Adapt the threshold check for OBFT

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#339]
In the spec it is stated that we should use `t = 0.22` where `t` is used in the following rule:

![image](https://user-images.githubusercontent.com/175315/53269183-7bde7580-36e8-11e9-8b01-92fff8fcd817.png)

However this check is implemented as:

```haskell
checkDelegator :: BlockCount -> PublicKey -> SigningHistory -> Bool
checkDelegator byzantineNodes s sh =
  delegatorSlots % 1 <= shK sh % byzantineNodes
 where
  delegatorSlots =
    fromMaybe 0 $ M.lookup (mkStakeholderId s) (shStakeholderCounts sh)

-- | The history of signers in the last @K@ blocks
--
--   We maintain a map of the number of blocks signed for each stakeholder to
--   improve performance. The sum of the `BlockCount`s in the map should be
--   equal to the length of the sequence.
data SigningHistory = SigningHistory
  { shK                 :: !BlockCount
  , shSigningQueue      :: !(Seq StakeholderId)
  , shStakeholderCounts :: !(Map StakeholderId BlockCount)
  } deriving (Eq, Show, Generic, NFData)
```

where `byzantineNodes = 5`. We should adapt the check so that it becomes something like:

```haskell
  delegatorSlots % 1 <= shK sh % (11/50)
```

If we choose to use a constant name for `11/50` then we also need to find a more appropriate name than `byzantineNodes`.

CC: @nc6 @ruhatch

**Comment by ruhatch** [comment]
I believe this has moved to ouroboros-networking now, so is no longer an issue in this repo
