### ISSUE TITLE
Do we want to keep using brittany?

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#340]
As programmers we should use our good judgement in formatting the code, optimizing it for readability. If we rely on automatic tools we get results like the following:

![image](https://user-images.githubusercontent.com/175315/53269541-6e75bb00-36e9-11e9-9da8-d9349746910a.png)

where the arguments to a function appear below and to the left of the function name. Or results like this one:

![image](https://user-images.githubusercontent.com/175315/53269611-a1b84a00-36e9-11e9-8932-1caea005bec8.png)

which produces a weird `case` alignment just because the tool wants to obey the `80` characters limit.

Paraphrasing Edsko:

> We take great care in our layout, which we use to emphasize the structure.

So we shouldn't let a tool take precedence over our sense of judgement.

But like always, feel free to close this issue if the majority wants to keep `brittany` :)

**Comment by ruhatch** [comment]
Personally I wouldn't consider either of these examples to be particularly bad. I see two main upsides to using this: 1) We get consistent formatting across the codebase, which increases readability once one becomes used to the particular style, and 2) we don't have to make decisions about formatting.

I agree there are some cases where things come out a little weird, especially guards, but I think we should aim to modify the tool and increase its configurability so we can get something good enough.

**Comment by erikd** [comment]
> We get consistent formatting across the codebase

I am generally in favor of this

> which increases readability once one becomes used to the particular style

But here I disagree. There are many automatic formatting features which I find drastically *decrease* readability and no matter how long I read code in that style, I still find if more difficult to parse and understand than code written in the style I would write it in. My biggest pet peeve is that (in `cardano-sl`) we limit line widths to 80 characters, and then for function calls with a lot of parameters, the parameters are each put on a separate line. The basis of this pet peeve (which I understand others may not share) is that I often work on a laptop and therefore want to use vertical space sparingly.

**Comment by erikd** [comment]
As an example of what in my opinion is poorly auto-formatted code, I give you:
```
checkApplicationName
  :: MonadError ApplicationNameError m => ApplicationName -> m ()
checkApplicationName (ApplicationName appName)
  | T.length appName > applicationNameMaxLength = throwError
  $ ApplicationNameTooLong appName
  | T.any (not . isAscii) appName = throwError $ ApplicationNameNotAscii appName
  | otherwise = pure ()
```
Any haskell coder reading that would know that `|` and `$` do not belong at the same indentation level.

Valid (in my opinion) ways of indenting that would be:
```
  | T.length appName > applicationNameMaxLength =
    throwError $ ApplicationNameTooLong appName
```
or
```
  | T.length appName > applicationNameMaxLength = throwError
    $ ApplicationNameTooLong appName
```

**Comment by dnadales** [comment]
> I agree there are some cases where things come out a little weird, especially guards, but I think we should aim to modify the tool and increase its configurability so we can get something good enough.

My first intuition would be that encoding what an appropriate format is is impossible. There are just too many variations, exceptions to the rule, and corner cases to consider, that at the end, no matter how many patches we submit to `brittany` we might end up with a deficient formatting tool anyway.

**Comment by dnadales** [comment]
Again, I think there are too many corner case for a tool to handle. I'm not satisfied at all with the results of the automatic formatting, specially when we have nested `if`s:

https://github.com/input-output-hk/cardano-chain/pull/353/commits/7f111f2a476ba3be27af830a1d7235b4ecea5ec1

**Comment by dnadales** [comment]
Brittany even fails on this simple code change https://github.com/input-output-hk/cardano-chain/pull/357/files

This forces us to re-run all of our CI tasks.
