### ISSUE TITLE
Simplify proxy signing

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#348]
After #347 the `ProxySecretKey` will be called `ProxyVerificationKey`. This is being used as a delegation certificate and nothing else, but is designed as a more general scheme. I think we should remove this premature abstraction, so I propose to:
- Remove the `omega` parameter and concretise to `EpochIndex`
- Inline the definitions from `ProxySecretKey` to `Delegation.Certificate`
- Perhaps change the name to `Delegation.OperationalCertificate` for forwards compatibility with Shelley

**Comment by AskAlexSharov** [comment]
Looks like done by https://github.com/input-output-hk/cardano-ledger/issues/321

**Comment by dnadales** [comment]
Hi @AskAlexSharov! Thanks for checking this out.

If I'm not mistaken, these are two different issues: #321 was closed by #347, but [currently](https://github.com/input-output-hk/cardano-ledger/blob/b6bb4f9d288820c2eb26059a4d70b69cd3d26eec/crypto/src/Cardano/Crypto/Signing/Proxy/VerificationKey.hs#L56) we still have an omega (`aPskOmega`) parameter lying around in `ProxyVerificationKey`:

```haskell
-- | Convenient wrapper for secret key, that's basically ω plus
-- certificate.
data AProxyVerificationKey w a = UnsafeAProxyVerificationKey
  { aPskOmega     :: Annotated w a
  , pskIssuerPk   :: PublicKey
  , pskDelegatePk :: PublicKey
  , pskCert       :: ProxyCert w
  } deriving (Eq, Ord, Show, Generic, Functor)
    deriving anyclass NFData
```

And the other two tasks mentioned in this issue still need to be done.

**Comment by ruhatch** [comment]
In order to make progress on this I need to decide what to do with `ProxySignature` first. My initial plan is to remove `ProxySignature` entirely, unifying `proxySign` with the regular `sign` function. This requires a modification to the `SignTag` type that will allow the `sign` function to append the `VerificationKey` in the prefix. So we need to:

## Next Actions
- [x] Modify the `SignTag` type to use `VerificationKey` in the `SignBlock` constructor
- [x] Replace calls to `proxySign` and `proxyVerify` with `sign` and `verify` calls
- [x] Split `BlockSignature` into two parts in `Header` and preserve binary format
- [x] Remove `ProxySignature` entirely

**Comment by ruhatch** [comment]
PR #541 takes care of the `ProxySignature`. The next step is to move the `ProxyVerificationKey` to `cardano-ledger` as `Delegation.Certificate`. We should also move across the tests from `Test.Cardano.Crypto.Signing.Proxy`.

## Next Actions
- [ ] Inline definition of `ProxyVerificationKey` to `Delegation.Certificate`, specialising to `EpochIndex`
- [ ] Move the tests over to `cardano-ledger`
- [ ] Split the `BlockSignature` into two in the `Header`, preserving binary format
