### ISSUE TITLE
Remove `AddrStakeDistribution`

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#356]
## Background

The `AddrStakeDistribution` type would have been used to represent different ways of assigning stake in Ouroboros Classic. It was never actually used on chain, apart from the `BootstrapEraDistr` nullary constructor. We will not use this type in the Shelley era as our address format will be changing, so we should simply drop the whole thing.

## Proposed Solution

We should remove this type entirely. To preserve compatibility with cardano-sl, we need to decode and encode the empty list, which was used to represent the `BootstrapEraDistr` constructor.

**Comment by ruhatch** [comment]
## Next Action
- [x] Modify `AddrAttributes` to drop `AddrStakeDistribution` and update the `Bi` instance

**Comment by mhuesch** [comment]
Late to the party -

I wasn't aware of the purpose behind `AddrStakeDistribution` in OClassic. If we only ever used `BootstrapEraDistr`, and it will change, then it seems unnecessary to keep around. So the PR looks justified and correct.
