### ISSUE TITLE
Make `withTests` counts configurable

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#363]
## Background
While studying `cardano-chain` as part of my getting-up-to-speed prep, I came across [this comment](https://github.com/input-output-hk/cardano-chain/blob/03cf7207c4961fec6ca22a074759b9cd4014fa06/test/Test/Cardano/Chain/Block/Validation/Spec.hs#L59-L61):
```
  -- TODO: we might want to make this configurable, so that we run a smaller
  -- number of tests when developing, and use a higher number when on CI (or in
  -- nightly builds?).
```
This reminded me of test sluggishness we had back on `cardano-sl`, which I always meant to get around to making configurable by situation (CI / local dev / nightly) but never did.

I wanted to make an issue so we track this and prioritize it appropriately. It likely isn't super-high priority, given that I don't think PR times, or local dev test run times are a bottleneck (but then again, I haven't been developing actively, so I don't know).

## Proposed Solution

(This is very much conditional on if we stick with Hedgehog, versus switching to Quickcheck. I am only going to provide a proposal for Hedgehog now, but the Quickcheck version should look similar)

In most of our test modules we use:
```
tests :: IO Bool
tests = checkParallel $$discover
```
to find a test `Group` and execute it. We then import them all into the top-level `test/test.hs` executable which [runs all of them via `runTests`](https://github.com/input-output-hk/cardano-chain/blob/03cf7207c4961fec6ca22a074759b9cd4014fa06/test/test.hs#L30-L51).

My suggestion is to write a new version of `discover` which will find things of type `Int -> Property` (where the `Int` is the test scalar) and package them into something of type `Int -> Group` (where the argument is threaded to all respective properties). Properties declared like `prop_<...> testScalar` would then use `withTests (3*testScalar` to scale their test counts.

Thus we would have something like:
```
tests :: Int -> IO Bool
tests scalar = checkParallel ($$discoverScaled scalar)
```
and, in the top-level executable:
```
main :: IO ()
main = do
  opts <- execParser optsParser
  let scenario = optsTestScenario opts
  testScalar <- getEnv "TEST_SCALAR"
  runTests $ map ($ testScalar)
    [ Test.Cardano.Chain.Block.Bi.tests
    ...
    ]
```
to thread the test scalar into the test groups.

### Benefit

Developers can run tests locally with a low `TEST_SCALAR`, perhaps 10, to get speedy test results, with probabilistically lower guarantees of correctness (but still "enough", ideally).

CI can run tests with `TEST_SCALAR=100` or so (approximating the current values of test counts). Since CI should be run fewer times than local dev, we get better assurance with a longer wait which happens infrequently.

Nightly tests can be run with `TEST_SCALAR=500` or more, to get high assurance. We get even better assurance, with longer wait, but even more infrequent.

This allows us scale the assurance of correctness we want.

**Comment by mhuesch** [comment]
## Next Action(s)
- [x] Await decision on Hedgehog vs Quickcheck
- [ ] Implement (I don't think this is more than 1 days work, although review could take a while)
- [x] Remove [related comment](https://github.com/input-output-hk/cardano-ledger/blob/168a7ee7cf984b219b41cbe0c4f408a613a8427a/test/Test/Cardano/Chain/Block/Validation/Spec.hs#L59)

**Comment by mhuesch** [comment]
I realize this isn't a very high priority item, but I had a plan in mind and wanted to get it down in text while it's fresh.

**Comment by dnadales** [comment]
> This is very much conditional on if we stick with Hedgehog, versus switching to Quickcheck. 

Notice that the question on whether we should stick to `hedgehog` or use `QuickCheck` concerns only the validation of generated chains. For the remaining tests I think we will still use `hedegehog`, even if we switch to `QuickCheck` for testing generated chains.

**Comment by mhuesch** [comment]
@dnadales ah, thanks for that! I had only heard bits and pieces of the discussion and thought it was a global problem. Thanks for clarifying.

In this case, I think the plan is feasible. My estimate of 1 day of work might be optimistic (for completing the whole thing) but in 1 day I think that 1 engineer would be able to assess the feasibility and implement most of it.

**Comment by ruhatch** [comment]
Yeah, go for it with `hedgehog` - you might be able to do something with the `Test.Options` stuff I defined for this kind of thing :)

**Comment by mhuesch** [comment]
@ruhatch Oh, great suggestion. You were thinking ahead! 🙂
