### ISSUE TITLE
Duplicated `Error` datatype

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-ledger-byron#390]
## Background
There are a few data types with the same name `Error` in the code:
In `Update`:
[Validation/Endorsement](https://github.com/input-output-hk/cardano-ledger/blob/master/src/Cardano/Chain/Update/Validation/Endorsement.hs#L61)
[Validation/Interface](https://github.com/input-output-hk/cardano-ledger/blob/master/src/Cardano/Chain/Update/Validation/Interface.hs#L76)
[Validation/Registration](https://github.com/input-output-hk/cardano-ledger/blob/master/src/Cardano/Chain/Update/Validation/Registration.hs#L44)
[Validation/Voting](https://github.com/input-output-hk/cardano-ledger/blob/master/src/Cardano/Chain/Update/Validation/Voting.hs#L51)
In `Txp`:
[Txp/Validation](https://github.com/input-output-hk/cardano-ledger/blob/2baeb495ec4fbf7928843a822f13fdcd1e28cd7d/test/Test/Cardano/Chain/Txp/Validation.hs#L79)

## Proposed Solution

I think these could be renamed to give more context?

**Comment by dnadales** [comment]
The idea is to use these error types qualified. Do you see any potential problems with it?

CC: @nc6 @ruhatch

**Comment by erikd** [comment]
The alternative is `EndorsementError`, `InterfaceError` and so on. Personally I prefer this, but I can lve with how it is now.

**Comment by dnadales** [comment]
> The alternative is EndorsementError, InterfaceError and so on. Personally I prefer this, but I can lve with how it is now.

I'm fine changing things back if that's better. I thought there was a preference for using certain identifiers qualified. I'm curious though about why do you prefer to have different names. Are there any disadvantages to the qualified approach?

**Comment by ruhatch** [comment]
I prefer the qualified approach personally, but we should make this an explicit style choice for the code base, rather than leaving it up to individual taste!

**Comment by ruhatch** [comment]
Closing, as we're using `qualified` imports approach
