### ISSUE TITLE
Add `CONTRIBUTING.md` that includes styles

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#399]
## Background

We currently don't keep track of style decisions that we are using in this codebase, for example, no lenses, or a preference for qualified imports.

## Proposed Solution

We should create a contributing document that keeps track of these explicit style choices and can then be referenced during review.

**Comment by dnadales** [comment]
Should this document include general guidelines like a "boy scout rule" whereby we should always try to piggyback small improvements like adding comments to undocumented functions, improving existing comments, etc?

**Comment by ruhatch** [comment]
> "Leave cardano-ledger a little better than you found it" 
_- Robert Baden-Powell_

**Comment by dnadales** [comment]
Another thing to address: short names vs. long names. When it is appropriate to use one or the other. I thought I was the only one using short names in `cardano-ledger` but I've seen other people using them in some places, so I wonder what's the rule of thumb. It'd be nice to have this either in the `CONTRIBUTING` document, or in a style guide linked from `CONTRIBUTING`.

**Comment by dnadales** [comment]
Maybe also for the style guide: when appropriate design your module to be used qualified. This shortens the identifier names. E.g. instead of:

```haskell
module Registration ( ... ) where 

data RegistrationError = RegistrationFoo ...
                       | RegistrationBar ...
````

we can have:

```haskell
module Registration ( ... ) where 

data Error = Foo ...
           | Bar ...
````

And at the usage site:

```haskell
import qualified Registration

... Registration.Error ...
... Registration.Foo ...
```
