### ISSUE TITLE
Bring `Address`-related golden and roundtrip tests over from `cardano-sl`

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#400]
## Background

There are `Aeson` and `Bi` and `Canonical` instances for `Address`, which are not currently (as of fb61626) under test.

## Proposed Solution

Bring over the golden & roundtrip tests from `cardano-sl` for `Address`. Suggested module names: `Test.Cardano.Chain.Common.Bi` & `Test.Cardano.Chain.Common.Json`.

**Comment by mhuesch** [comment]
## Next Action
- [x] Bring the tests over
  - [x] `Test.Cardano.Chain.Slotting.Bi`
  - [x] `Test.Cardano.Chain.Slotting.Json`
  - [x] `Test.Cardano.Chain.Common.Bi`
  - [x] `Test.Cardano.Chain.Common.Json`

**Comment by ruhatch** [comment]
Yeah, I think I missed `Test.Cardano.Chain.Common.Bi` and `Test.Cardano.Chain.Slotting.Bi`! Not sure how that happened, but good spot!

**Comment by mhuesch** [comment]
@ruhatch I forgot to mention above, but credit for noticing this is to @intricate! I've added a todo item for `Test.Cardano.Chain.Slotting.Bi` as well, thanks for pointing that out.
