### ISSUE TITLE
feature request: Ledger blue support

### ISSUE THREAD

**Issue by veilgets** [input-output-hk/cardano-ledger-byron#404]
I recently saw that Cardano offers ledger nano s/x support, please also consider supporting ledger blue.

**Comment by ruhatch** [comment]
This is unrelated to this repository

**Comment by dnadales** [comment]
Hi @veilgets, for additional information see [this post](https://www.reddit.com/r/ledgerwallet/comments/7zbcye/ledger_blue_discontinued/):

> In July 2018, Ledger announced that it would be releasing a final batch of 10,000 Ledger Blue wallets. Once sold, the wallet will no longer be available to purchase. The Ledger Blue is a handheld hardware wallet designed to store cryptocurrency. Jan 18, 2019

For similar requests feel free to send a message in the [Cardano forum](https://forum.cardano.org/).
