### ISSUE TITLE
Create `Diff` typeclass

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#410]
## Background

```
-- | A class for values where we can calculate the difference between values
-- and layer apply (or \"patch\") the difference
```

@dcoutts provided a starting point, which I've attached here: [Diff.hs.txt](https://github.com/input-output-hk/cardano-ledger/files/3040654/Diff.hs.txt). The above quote is a comment in the module.

My (@mhuesch) understanding is that this class will
* be used to diff values in the ledger state.
* need to produce stable representations, which may go over the wire and communicate with different implementations / different codebases.
* require instances for core ledger datatypes, in addition to produce types, sets, maps
* likely only require diffs at the "set and map level". We will have large sets of "small elements" where we're less interested in diffing items against each other than we are diffing sets/maps (containing such elements) against each other.

@dcoutts says:

> Diff class.
> 
> Note that the `Map` instance is not yet complete since it does not yet do the diffing for changed entries. The QC properties demonstrate this incompleteness.
> ```
> *Cardano.Chain.Diff> quickCheck prop_patchDiff_Map 
> *** Failed! Falsifiable (after 4 tests and 7 shrinks):    
> fromList [(0,0)]
> fromList [(0,1)]
> ```
> Doing this bit will require using the `Data.Map.Merge` stuff.

## Proposed Solution

Flesh out the typeclass, flesh out the property tests for generic types, establish property tests for ledger-specific types so we have concrete test cases.

**Comment by mhuesch** [comment]
## Next Action
- [ ] Start from attached module.
- [ ] Implement Map instances - make Map property tests pass
- [ ] Write properties involving real ledger datatypes
- [ ] Make ⬆️ ledger properties pass by filling in instances

**Comment by nc6** [comment]
@mhuesch Is this issue still relevant?

**Comment by dcoutts** [comment]
I think we will not need this in the end.

https://github.com/input-output-hk/ouroboros-network/pull/1209

It looks like this design with state query will work out and we will not need incremental state update using diffs.
