### ISSUE TITLE
Rename `Chain` to `Ledger` in namespaces

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-ledger-byron#421]
## Background

`Chain` is used in the name space of directories & modules.

## Proposed Solution

Rename `Chain` to `Ledger`

**Comment by ruhatch** [comment]
The divide between `Chain` and `Ledger` isn't entirely clear, so we should think about this one some more. I think `Cardano.Chain.TxP` to `Cardano.Ledger.UTxO` makes a lot of sense, but some of the others need more thought.

**Comment by ruhatch** [comment]
Duplicate of #184
