### ISSUE TITLE
Investigate replacing uses of `Buildable`/`build` with explicit `renderX` functions

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#427]
## Background

See discussion [here](https://github.com/input-output-hk/cardano-ledger/pull/394#discussion_r270123283), regarding [this block of code](https://github.com/input-output-hk/cardano-ledger/blob/94385476141aa64b7ec5f1aab61ac4d3cf631d07/src/Cardano/Chain/Block/Block.hs#L146-L152).

`build` is highly polymorphic, so if an argument's type is changed we are not alerted by type errors, which would indicate breakage. 

## Proposed Solution

This issue should represent an investigation of how much work it would be to switch all of the `build` definitions to explicitly typed `renderX` functions. For example,

https://github.com/input-output-hk/cardano-ledger/blob/7fc058becc271f42101c34c7b52004daf768aa7e/crypto/src/Cardano/Crypto/Signing/Tag.hs#L54-L55

would be rewritten as
```
renderSignTag :: SignTag -> Text
renderSignTag = show
```

The `renderX` functions could also be written reusing the bodies of their `build` definitions, using [`format`](https://www.stackage.org/haddock/lts-13.4/formatting-6.3.7/Formatting.html#v:format).

**Comment by mhuesch** [comment]
## Next Action
- [ ] Investigate how much work is required to change all `build` / `Buildable` instances with `renderX` functions.
- [ ] Decide if it's worth making the change.
- [ ] If yes, create an issue for and/or complete a PR to make the changes.

**Comment by dnadales** [comment]
Silly question maybe: why are multiple `renderX` functions, instead of having it being part of a type-class? As far as I understand the problem with `bprint` is how polymorphic it is. But if we would use the `renderX` family of functions this won't be a problem.

Am I missing something?

**Comment by mhuesch** [comment]
I think that Ru was going for a very explicit & typesafe way of printing things, so that we're alerted to breakage. But that is more verbose than a typeclass. So I'm not sure. I don't think you're missing something.

**Comment by dnadales** [comment]
> I think that Ru was going for a very explicit & typesafe way of printing things

But I guess a typeclass that has a `render` function should give us that (with less verbosity) without having the pitfalls of the `bprint` function. @ruhatch , @erikd any ideas?

**Comment by ruhatch** [comment]
@dnadales I have a problem with the `build` function! `bprint` is actually not an issue as long as the constituent builders aren't too polymorphic. If you use `bprint` with an explicit `renderX` then changing the type of `X` will result in a type error. The poly-variadic part is actually okay!

**Comment by dnadales** [comment]
Hmmm, but then what the advantage of using `bprint` over good old text concatenation using monoids?

And @ruhatch don't you think several `renderX` might be too verbose?

**Comment by ruhatch** [comment]
So I guess one advantage of `bprint` is separating the render functions from the values a little:
```haskell
renderBlock :: EpochSlots -> Block -> Format r (Block -> r)
renderBlock es = later $ \block -> bprint
    ( "Block:\n"
    . "  " . renderHeader . "  transactions (" . int . " items): " . listJson . "\n"
    . "  " . Delegation.renderPayload . "\n"
    . "  " . Ssc.renderPayload . "\n"
    . "  update payload: " . Update.renderPayload . "\n"
    . "  " . renderExtraData
    )
    (WithEpochSlots es $ blockHeader block)
    (length txs)
    txs
    (blockDlgPayload block)
    (blockSscPayload block)
    (blockUpdatePayload block)
    (blockExtraData block)
  where txs = bodyTxs $ blockBody block
```
Here I've turned `renderBlock` into a `Format`, so that we could use it in further `Format`s

**Comment by dnadales** [comment]
Sorry that I keep on insisting with this, but I'm still a bit confused. If `render` would return a `Text`, what would be the advantages of the above w.r.t. simply defining:

```haskell
renderBlock :: EpochSlots -> Block -> Text
renderBlock es =
     "Block:\n"
     <> "  " <> hdr <> "  transactions (" <> ntxs <> " items): " <>  txs <> "\n"
     <> "  " <> delegationPayload . "\n"
     <> "  " <> sscPayload <> "\n"
     <> "  update payload: " <> updatePayload <> "\n"
     <> "  " <> extraData
  where
    hdr = renderHeader $ WithEpochSlots es $ blockHeader block
    txs = ...
```

**Comment by erikd** [comment]
@dnadales In your `renderBlock` immediately above, you have numerous `mappend` operations. That code could better be wriiten as a single `concat` operations like:
```haskell
renderBlock :: EpochSlots -> Block -> Text
renderBlock es =
   Text.concat
     [ "Block:\n"
     , "  ", hdr, "  transactions (", ntxs, " items): " ,  txs, "\n"
     , "  ", delegationPayload, "\n"
     ,"  ", sscPayload, "\n"
     ,"  update payload: ", updatePayload, "\n"
    , "  ", extraData, "\n"
    ]
  where
    hdr = renderHeader $ WithEpochSlots es $ blockHeader block
    txs = ...
```

**Comment by ruhatch** [comment]
I don't think this is worth the effort, so I'm going to close it

**Comment by dnadales** [comment]
> @dnadales In your `renderBlock` immediately above, you have numerous `mappend` operations. That code could better be wriiten as a single `concat` operations like:
> 
> ```haskell
> renderBlock :: EpochSlots -> Block -> Text
> renderBlock es =
>    Text.concat
>      [ "Block:\n"
>      , "  ", hdr, "  transactions (", ntxs, " items): " ,  txs, "\n"
>      , "  ", delegationPayload, "\n"
>      ,"  ", sscPayload, "\n"
>      ,"  update payload: ", updatePayload, "\n"
>     , "  ", extraData, "\n"
>     ]
>   where
>     hdr = renderHeader $ WithEpochSlots es $ blockHeader block
>     txs = ...
> ```

Somehow I missed your comment @erikd :/ Thanks.
