### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#428]
## Background

Relates to #400.

We would like better test coverage, as a baseline for assurance that our code is well tested and correct.

## Proposed Solution

* Identify any missing test modules which weren't brought over from `cardano-sl` to `cardano-ledger`
* Look at modules which have low code coverage as reported by https://coveralls.io/github/input-output-hk/cardano-ledger

- [ ] Compile a list of other modules which are lacking coverage, so address this whole category of problem, rather than doing them in a one-off fashion 🙂

Use [Jordan's past PRs](https://github.com/input-output-hk/cardano-ledger/issues?q=is%3Aissue+author%3AJimbo4350+is%3Aclosed) to see which tests have already been brought over.

**Comment by mhuesch** [comment]
## Next Action
- [ ] Compile list
- [ ] Create issues for moving any modules over
    * OR just raise a PR moving the modules over

**Comment by mhuesch** [comment]
Another way to raise coverage % is to exclude derived instances which we can safely assume are correct.

It seems that we could either write dummy functions to exercise all instances, or we can try to mess around with the `.tix` files via overlaying:
https://stackoverflow.com/questions/46481633/how-can-i-generate-a-coverage-overlay-with-hpc-and-stack
https://stackoverflow.com/questions/25797720/how-to-exclude-derivation-of-show-from-hpcs-code-coverage

**Comment by ruhatch** [comment]
In general I'd like to exclude some functionality, such as `Buildable` instances that have nothing to test! I guess we could test that they don't crash, so just add `eval $ sformat build exampleValue` or something?
