### ISSUE TITLE
Encode mainnet `Genesis.Config` as a Haskell datatype, and check consistency with `test/mainnet-genesis.json` in a Property

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#432]
## Background

See background [here](https://github.com/input-output-hk/cardano-ledger/pull/394#discussion_r270530544). We can avoid unnecessarily reading the on-disk config by putting it in a datatype.

Add a Property somewhere to check that they match up.

## Proposed Solution

See ⬆️

**Comment by mhuesch** [comment]
## Next Action
- [ ] Write an pure datatype
- [ ] Write a property
- [ ] Replace occurrences of `mainnetEpochSlots` with a view into said pure datatype

**Comment by ruhatch** [comment]
One problem with this is how large the balances are in the mainnet genesis config, but maybe that's okay

**Comment by mhuesch** [comment]
> One problem with this is how large the balances are in the mainnet genesis config, but maybe that's okay

Not sure I understand - why does balance size matter for encoding it as a Haskell datatype?

**Comment by ruhatch** [comment]
Just would be a massive source file is all!
