### ISSUE TITLE
`goldenTestBi` output is stifled

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-byron#435]
## Background

`goldenTestBi` has nice functionality for good error messages. However its output seems to be getting stifled somehow:
```
━━━ Test.Cardano.Chain.Slotting.Bi ━━━
  ✓ golden_EpochIndex passed 1 test.
  ✗ golden_FlatSlotId failed after 1 test.

    This failure can be reproduced by running:
    > recheck (Size 0) (Seed 2264516985870913048 455201420688529847) golden_FlatSlotId

  ✓ golden_LocalSlotIndex passed 1 test.
  ✓ golden_EpochSlots passed 1 test.
  ✓ golden_SlotId passed 1 test.
  ✗ 1 failed, 4 succeeded.
```
(test printouts from a run of `stack test cardano-ledger:test:cardano-ledger-test`)

## Proposed Solution

Unsure; requires investigation.

**Comment by mhuesch** [comment]
## Next Action
- [ ] Identify the what is causing output to be stifled and fix it 🙂

**Comment by mhuesch** [comment]
This is impacted by the splitting of `Bi` into `FromCBOR` and `ToCBOR`. We will likely use

https://github.com/input-output-hk/cardano-base/blob/8062dba12b0175a6029101edb46dd59e9f9116ae/binary/test/Test/Cardano/Binary/Helpers/GoldenRoundTrip.hs#L88-L94

instead, which may or may not have the same stifling issues.

**Comment by ruhatch** [comment]
This is usually a `HasCallStack` issue!

**Comment by ruhatch** [comment]
Might be fixed by updating to this https://github.com/input-output-hk/cardano-base/pull/9

**Comment by mhuesch** [comment]
@ruhatch thanks! 🙌
