### ISSUE TITLE
Audit memory use of full ledger state during chain validation

### ISSUE THREAD

**Issue by intricate** [input-output-hk/cardano-ledger-byron#439]
## Background

In PR #411, RTS options were added to the tests in order to limit the memory usage: `"-with-rtsopts=-K450K -M200M"`

However, in PR #434, it appears that we now require more than twice as much heap memory for a successful run of the test suite (we've limited the heap to `500M` now).

## Proposed Solution

We should perform some heap profiling while validating the chain with the full ledger state in order to determine whether there are any memory leaks.

**Comment by Jimbo4350** [comment]
@intricate This may be useful: https://github.com/input-output-hk/cardano-ledger/pull/441

**Comment by intricate** [comment]
Relevant: PR #489 was merged which adds a test that asserts that the `ChainValidationState` is in normal form after applying each epoch during the mainnet epoch validation tests. A hydra job was added to run this test as well.
