### ISSUE TITLE
Build LaTeX specs with CI

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-byron#49]
There are makefiles inside `cardano-chain/specs/ledger/latex/` and `cardano-chain/specs/chain/latex/` which build pdfs.  It would be nice to check these builds as a part of CI.

**Comment by ruhatch** [comment]
It would be awesome to have the results downloadable as buildkite artifacts - @rvl is that possible/reasonable?

**Comment by dnadales** [comment]
To have the CI build only branches where latex files have changes we could use the following command:

```sh
git whatchanged --name-only --pretty="" origin..HEAD | grep \\.tex
```

And check if that command gives back a non-empty result.

**Comment by dnadales** [comment]
> To have the CI build only branches where latex files have changes we could use the following command:

No need to do this if we use hydra for caching ...
