### ISSUE TITLE
Possible negative multiplication in scaleLovelace function

### ISSUE THREAD

**Issue by mitros123** [input-output-hk/cardano-ledger-byron#496]
Hello. The [`scaleLovelace`](https://github.com/input-output-hk/cardano-ledger/blob/9bb8278b5b2b65e2ddd1df265b93cb68a13aa619/src/Cardano/Chain/Common/Lovelace.hs#L174) function does not check for a negative b. This might be a problem.

```
-- | Scale a 'Lovelace' by an 'Integral' factor, returning 'LovelaceError' when
--   the result is too large
scaleLovelace :: Integral b => Lovelace -> b -> Either LovelaceError Lovelace
scaleLovelace (unsafeGetLovelace -> a) b
  | res <= lovelaceToInteger (maxBound :: Lovelace) = Right
  $ Lovelace (fromInteger res)
  | otherwise = Left $ LovelaceTooLarge res
where res = toInteger a * toInteger b
```

The issue also extends to the `div` and `mod` functions below it.

**Comment by wuggen** [comment]
[`calculateTxSizeLinear`](https://github.com/input-output-hk/cardano-ledger/blob/33c74add509e21d92bc9428d7ed82f9665120c17/src/Cardano/Chain/Common/TxSizeLinear.hs#L77) is affected by this.
