### ISSUE TITLE
Audit Generators for use of `Monad` instance

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#503]
## Background

@edsko published a [blog post](http://www.well-typed.com/blog/2019/05/integrated-shrinking/) discussing integrated shrinking and specifically why a `Monad` instance for `Gen` is a bad idea.

## Proposed Solution

Audit the generators for uses of the `Monad` interface and either replace them with applicative, if possible, or manual shrinking where necessary.

## Next Actions
- [ ] Audit codebase for generators using the Monad interface
- [ ] Update generators to use applicative or manual shrinking

**Comment by dnadales** [comment]
> ￼ Update generators to use applicative or manual shrinking

Side note, we really need to have good abstractions for writing manual integrated shrinkers. The original justification on the use of `hedgehog` was:

> People are lazy so they don't write shrinkers

But now that we know that we need to write shrinkers in some (many?) cases anyway, the reasoning above translates to:

> People are lazy so they don't write shrinkers. We need to write shrinkers anyway. Let's make it hard for the average (Haskell) programmer to write shrinkers.

**Comment by ruhatch** [comment]
@dnadales I agree - hopefully writing several non-trivial generators will reveal a pattern, so we can produce a good abstraction
