### ISSUE TITLE
Initial delegation certificates are applied incorrectly

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#504]
## Background

In `Cardano.Chain.Delegation.Validation.Interface`, initial delegation is specified by:
- Firstly, constructing an initial delegation map which delegates from stakeholders to themselves.
- Secondly, applying the certificates from the genesis data in the normal way.

The problem is that normally, delegation certificates do not come into effect from the moment they are posted - they are only scheduled, and will come into effect at some future slot. For the genesis configuration, this is incorrect - the initial delegation should be in effect from the first block.

## Proposed Solution

Change `initialState` to create the delegation map directly using the heavyweight delegation certificates, rather than calling `updateDelegation`.

## Next Action
- [x] Confirm this diagnosis (@ruhatch?)
- [ ] Fix all the things

**Comment by ruhatch** [comment]
A simple solution that I've tested out locally is to replace `k` with `0` in the environment that you pass to `updateDelegation`, which will let them be adopted instantly.
