### ISSUE TITLE
Remove un-used functions

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-ledger-byron#557]
The functions `maxVerKeyAddressSize` and `maxHDAddressSize` were carried over from the old code base but are unused in the new code base.

* Can they be removed?
* If they can be removed, the `biSize` function in `cardano-binary` can also be dropped.

If they can be removed (these functions and `biSize`), then @DeepakKapiswe can do the work.

**Comment by ruhatch** [comment]
I don't know if the wallet needs them, but I think the idea is to have the wallet not depend on us anymore, so go ahead and remove them!

We can always bring them back when they're actually needed.
