### ISSUE TITLE
Add Expectation type for errors with various possibilities

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#559]
## Background

It would be good to have a more general type for returning in errors that captures unexpected results.

## Proposed Solution

It could be something along the lines of:

```
data Expected v = 
  Expected 
    { expectation :: Expectation
    , expected :: v
    , got :: v
    }

data Expectation =
    LessThan
  | MoreThan
  | Exactly
  | Other Text
```

## Next Action
- [ ] Implement something similar to above and trial on `ChainValidationError`

**Comment by dnadales** [comment]
:100: 

Although I'd say that this expectation refers to an ordering, so maybe we'd want something like `ExpectedOrdering` (although this sounds awful). 

Alternatively we might want to keep only the `Other Text` part :man_shrugging:
