### ISSUE TITLE
Size of TxAux

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/cardano-ledger-byron#576]
For the Mempool in the consensus layer, we need to know the size of a transaction (including its auxiliary data), i.e. the size of `Cardano.Chain.UTxO.ATxAux ByteString` in bytes.

Currently we have:
```haskell
import qualified Data.ByteString as Strict

txAuxSize :: ATxAux ByteString -> Word32
txAuxSize atxaux = fromIntegral txByteSize
  where
    txByteSize = 1
               + (Strict.length . annotation . aTaTx      $ atxaux)
               + (Strict.length . annotation . aTaWitness $ atxaux)
```
However, this feels a bit brittle: what if the format of `ATxAux` changes?

There is also the `encodedSizeExpr` method of `ToCBOR`, could this somehow be used here?

We would like a function in `cardano-ledger` that gives us the size of an `ATxAux ByteString` in bytes.

**Comment by ruhatch** [comment]
I imagine what we should really do here is add an annotation to the `ATxAux` and the take the size of that

**Comment by ruhatch** [comment]
Although equally the size of `ATxAux` isn't going to change, so the brittle one is also probably fine

**Comment by intricate** [comment]
@mrBliss: As a result of #660, I guess we can close this since we can now just do `length . recoverBytes`.
