### ISSUE TITLE
Fewer PBKDF2 iterations than what is recommended

### ISSUE THREAD

**Issue by mitros123** [input-output-hk/cardano-ledger-byron#585]
The Hierarchical Derivation interface [here](https://github.com/input-output-hk/cardano-ledger/blob/master/crypto/src/Cardano/Crypto/HD.hs#L85), [permalink](https://github.com/input-output-hk/cardano-ledger/blob/cdef85fb9ca98c3ccb61a98f6081d4e5060ff920/crypto/src/Cardano/Crypto/HD.hs#L85) uses fewer (500) PBKDF2 interations than what is suggested.
Copying from wikipedia: "When the standard was written in the year 2000 the recommended minimum number of iterations was 1000, but the parameter is intended to be increased over time as CPU speeds increase. A Kerberos standard in 2005 recommended 4096 iterations; Apple reportedly used 2000 for iOS 3, and 10000 for iOS 4; while LastPass in 2011 used 5000 iterations for JavaScript clients and 100000 iterations for server-side hashing."

While the number 500 does not break security in any immediate way, since the implementation deviates from the recommended number of iterations, it is something that is worth noting.

**Comment by SebastienGllmt** [comment]
FYI the Rust codebase uses 19162 iterations

More specifically here are the set of parameters used by the Rust codebase

```
    pub const ITER: u32 = 19_162;
    pub const SALT_SIZE: usize = 32;
    pub const NONCE_SIZE: usize = 12;
    pub const KEY_SIZE: usize = 32;
    pub const TAG_SIZE: usize = 16;
```

**Comment by SebastienGllmt** [comment]
Actually I noticed Rust-Cardano uses 4096 iterations for key derivations [here](https://github.com/input-output-hk/rust-cardano/blob/53d5e5fb8981523c124d2d1ebc2845bc6bdacfa8/cardano/src/wallet/keygen.rs#L14) whereas the 19_162 is used for password encryption of the key [here](https://github.com/input-output-hk/js-cardano-wasm/blob/bd40ab0f8d6ae27998c7ef5125c8c5cbd109a285/wallet-wasm/src/lib.rs#L1181)

**Comment by intricate** [comment]
This file was completely deleted as part of #674. 

Thanks for raising this issue, though!
