### ISSUE TITLE
Boundary validation data generator generates an impossible case

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#597]
## Background
The `ts_roundTripBoundaryBlock` test is failing:

```
           ┃       │ ━━━ Intermediate ━━━
                  ┃       │ "\131\133\NULX \170\215\138\DC3\181\n\SOHJ$c<}D\253\143\141\CAN\246{\187?\169\203\206\223\131J\200\153u\157\205X 9\223\STXJ\197'\"\254\138\228\193\168t\SOLV$\163\140\&8 \229\EOT\160Y\170\232r\132!\248\189\130\NUL\129\NUL\129\160\159\255\129\160"
                  ┃       │ ━━━ - Original/+ Roundtrip ━━━
                  ┃       │ - Boundary : Starting epoch : 0 aad78a13b50a014a Block number : (-0)
                  ┃       │ + Boundary : Starting epoch : 0 Genesis Block number : (-0)
```

There's a bug in the generator:

```haskell
genBoundaryValidationData :: Gen (BoundaryValidationData ())
genBoundaryValidationData = 
  BoundaryValidationData
    <$> pure 0
    <*> (Gen.choice [Right <$> genHeaderHash, Left . GenesisHash . coerce <$> genTextHash])
    <*> (Gen.word64 (Range.constantFrom 10 0 1000))
    <*> genChainDifficulty
    <*> pure ()
    <*> pure ()
```

It's possible to generate Right for the header hash, but 0 for the epoch. That case should be excluded.

## Proposed Solution

Fix it :wrench:

**Comment by dnadales** [comment]
@nc6 Question, [now](https://github.com/input-output-hk/cardano-ledger/commit/f07d57cf0b56b4609f1d9302713c8351bdda70bd) we have the following data structure:

```
data ABoundaryHeader a = UnsafeABoundaryHeader
  { boundaryPrevHash         :: !(Either GenesisHash HeaderHash)
  , boundaryEpoch            :: !Word64
  , boundaryDifficulty       :: !ChainDifficulty
  , boundaryHeaderAnnotation :: !a
  } deriving (Eq, Show, Functor, Generic, NoUnexpectedThunks)
```

We also have a smart constructor for `ABoundaryHeader`:

```
-- | Smart constructor for 'ABoundaryHeader'
--
-- Makes sure that the hash is forced.
mkABoundaryHeader :: Either GenesisHash HeaderHash
                  -> Word64
                  -> ChainDifficulty
                  -> a
                  -> ABoundaryHeader a
mkABoundaryHeader prevHash epoch dty ann =
    case prevHash of
      Left  !genHash -> UnsafeABoundaryHeader (Left  genHash) epoch dty ann
      Right !hdrHash -> UnsafeABoundaryHeader (Right hdrHash) epoch dty ann
```

I'm wondering whether this constructor should check the invariant that `not (boundaryEpoch be == 0) || isLeft (boundaryPrevHash be)`

**Comment by dnadales** [comment]
The second question has to do with the nature of the failure. I understand that the invariant above is implicitly assumed. However, I wonder why do we get such failure in the roundtrip test. Does de-serialization ignores the hash if it sees a `0` in the epoch?

**Comment by dnadales** [comment]
It seems we do:

https://github.com/input-output-hk/cardano-ledger/blob/5e0322caa11b1a46b70f16addb4b056bccf5696b/cardano-ledger/src/Cardano/Chain/Block/Header.hs#L523

But I don't get the error I see:

```
              ┃       │ ━━━ - Original/+ Roundtrip ━━━
              ┃       │ - Boundary : Starting epoch : 0 aad78a13b50a014a Block number : (-0)
              ┃       │ + Boundary : Starting epoch : 0 Genesis Block number : (-0)
```

**Comment by dnadales** [comment]
Ok, now I get it. It seems that de-serialization has to fit the hash in a left or right value.

So it seems that we should:

- fix the generators
- add a smart constructor 

@nc6 does this make sense to you?

**Comment by nc6** [comment]
Yes, the approach looks good!
