### ISSUE TITLE
Utilize TH to derive CBOR instances

### ISSUE THREAD

**Issue by intricate** [input-output-hk/cardano-ledger-byron#630]
From @mhuesch (https://github.com/input-output-hk/cardano-ledger/pull/628#issuecomment-527895288):

> @intricate I feel a little bad suggesting this _after_ you did all the work of manually implementing CBOR instances (wish I had asked you about the work earlier when you said you were starting it!), but could we use TH to derive these boilerplate-y instances?
> 
> I wrote https://github.com/input-output-hk/cardano-sl/blob/51ad7c0503b1c52a75a6eb36096c407934136468/binary/src/Pos/Binary/Class/TH.hs#L142-L143 in `cardano-sl` and that could probably be modified relatively easily to work with `ToCBOR`/`FromCBOR`. I had to exercise my TH-fu for goblins, so I am relatively fresh on this and could implement it if desired.
> 
> We probably want to check with someone with higher context, if there's a reason not to use TH to derive these.

From @mhuesch (https://github.com/input-output-hk/cardano-ledger/pull/628#issuecomment-527900111):

> Although, I just read the "Avoid TemplateHaskell" section of http://www.stephendiehl.com/posts/production.html 
> 
> I still think that in this case we're only deriving instances which look fairly manual to hand-write, so I think it is a legitimate use of TH. Now that the work is done, though, perhaps it's too late to justify implementing a TH derivation function.

How do others feel about utilizing TH for this purpose?

**Comment by mhuesch** [comment]
As @intricate & I discussed on Slack, it seems like boilerplate-y instances (`case`ing on a record, pulling fields out, recursively encoding them, concatenating encoded expressions into a list, serializing that. Or `case`-ing on a serialized tag, then pulling out the appropriate fields and recursively deserializing them into a record) are a good candidate for TH.

We might also want to consider Generics. I am not knowledgeable about Generics to say how performance & maintainability compare... But it seems like hand-writing instances vs using TH to generate equivalent instances would point to TH being more maintainable (less code, more of it in one place, debugging of incorrect instance implementation only must be done in 1 place - the TH function).

**Comment by intricate** [comment]
CC @ruhatch @erikd @dnadales

**Comment by erikd** [comment]
Ah the siren call of auto generated (derivied via Generics) serialisation.

Problem is that changes in things outside our control (ie the compiler) can change the auto generated serialisation formats. That was the reason for using TH in the old code base to explicitly order field names and indices in the derived `Bi` instances.

I have no problem with using TH like we had in the old code base but Generics could easily bite us here.

**Comment by mhuesch** [comment]
Agree with Erik that TH is a decent solution. However, @ruhatch had a more "social engineering" point about how with TH derivation available, devs might reach for that without considering if a more custom instance would be better in that individual case than a simplistic derived instances. So if we don't provide TH, then we have to hand-write everything and think about what is best in each case.

I think this is a reasonable point, and think we should just close this issue until the pain of manual instances proves to be significant enough to change the calculus. If that is the case, I'm happy to implement this TH derivation function.
