### ISSUE TITLE
Formalize the Byron update rules

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#64]
# Main Goal

Model the evolution of the [`BlockVersionData`](https://github.com/input-output-hk/cardano-sl/blob/a791f11bc3443628fd168f896dba93fe8d1f1d59/chain/src/Pos/Chain/Update/BlockVersionData.hs#L30) parameters in the ledger state.

## Aspects to be modeled

0. Authentication: the proposal needs to be properly signed.
1. Authorization: the proposal needs to be signed by the genesis keys or one of the delegates.
2. Voting: genesis key holders or delegates can only vote on a proposal after it is posted.
3. Voting deadlines: voting ends with a majority of the voters (4/7 if we assume no state) agree on a proposal. Bear in mind that a rule that finishes the voting period after 4/7 positive votes will succeed to validate the existing chain only if the distribution of the stake is roughly equal (which might not be the case, and we'd have to revisit this rule).
4. Block-version changes: when the voting ends, we need to update the block-chain parameters according to the proposed version.

# Current subtasks

- [x] Determine which information do we need to keep track of in the ledger state:
    - [x] A subset of the information in `BlockVersionData`.
    - [x] Something else?
- [x] Determine whether software updates are related to protocol (`BlockVersionData`) updates.

# References

- https://cardanodocs.com/technical/updater/
- https://cardanodocs.com/cardano/update-mechanism/
- https://github.com/input-output-hk/cardano-sl/blob/develop/docs/auxx.md#proposing-an-update
- https://github.com/input-output-hk/cardano-sl/blob/develop/wallet-new/docs/updates.md
- https://github.com/input-output-hk/cardano-sl/blob/develop/docs/proposals/update-downloader.md

**Comment by commandodev** [comment]
@dnadales Does this still need more breakdown?

**Comment by dnadales** [comment]
It'll be closed by PR #156. I'll open smaller issues as I get feedback on the draft I submitted in that PR.
