### ISSUE TITLE
Cache header hash

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/cardano-ledger-byron#641]
## Background

The hash of a header is recomputed every time it's used. The serialised bytestring is cached through the `Annotated` type, but hashing that bytestring still has a non-trivial cost.

In consenus, this showed up in the profiling output, so we have cached it for now: https://github.com/input-output-hk/ouroboros-network/pull/1049

## Proposed Solution

Cache the hash of the header in a lazily-computed field. Next, undo the caching done in ouroboros-network.

**Comment by edsko** [comment]
Closing, we do this consensus side.
