### ISSUE TITLE
Provide an update interface to the wallet

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#650]
## Background
The wallet needs access to the update part of the ledger state.

In addition, it would be nice if `cardano-ledger` could summarize that to a simple application version and installer hash (for the current platform) that can be passed straight to `daedalus`.

A JSON Schema of (approx) what information the wallet will provide:

```json
{
  "title": "Software Update information",
  "description": "Mapping of ApplicationName to latest confirmed proposal",
  "type": "object",
  "additionalProperties": {
    "type": "object",
    "required": [
      "applicationVersion",
      "installerHashes"
    ],
    "properties": {
      "applicationVersion": {
        "type": "integer",
        "minimum": 0
      },
      "installerHashes": {
        "type": "object",
        "description": "Mapping of SystemTag to InstallerHash",
        "additionalProperties": {
          "description": "Blake2b hash in hexadecimal",
          "type": "string",
          "minLength": 64,
          "maxLength": 64,
          "pattern": "^[0-9a-fA-F]*$"
        }
      }
    }
  }
}
```

**Comment by dcoutts** [comment]
@KtorZ can you confirm that you are choosing to follow a design where you query the node for the update state, rather than maintaining it incrementally block-by-block in the wallet? If so, then we do not need to expose this functionality in the ledger lib.

**Comment by KtorZ** [comment]
I confirm.

**Comment by dcoutts** [comment]
Thanks.

**Comment by dnadales** [comment]
BTW @redxaxder implemented this functionality. Do we want to remove it from `cardano-ledger`?
