### ISSUE TITLE
Remove unused error constructors in module Cardano.Chain.Block.Validation

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#670]
## Background
Consensus layer now checks a number of things that were previously checked at the ledger. However there were some errors constructors left, namely:

- [ ] `ChainValidationInvalidSignature`
- [ ] `ChainValidationBlockAttributesTooLarge`
- [ ] `ChainValidationHeaderAttributesTooLarge`
- [ ] `ChainValidationDelegationPayloadError`
- [ ] `ChainValidationInvalidDelegation`
- [ ] `ChainValidationMissingHash`
- [ ] `ChainValidationUnexpectedGenesisHash`
- [ ] `ChainValidationSignatureLight`
- [ ] `ChainValidationTooManyDelegations`

## Proposed Solution

Remove them.

**Comment by mrBliss** [comment]
There are more unused constructors: 
* `ChainValidationBlockAttributesTooLarge`
* `ChainValidationHeaderAttributesTooLarge`
* `ChainValidationDelegationPayloadError`
* `ChainValidationInvalidDelegation`
* `ChainValidationMissingHash`
* `ChainValidationUnexpectedGenesisHash`
* `ChainValidationSignatureLight`
* `ChainValidationTooManyDelegations`

**Comment by dnadales** [comment]
Thanks @mrBliss I will edit the issue description.

**Comment by mrBliss** [comment]
Duplicate of #575.
