### ISSUE TITLE
Move auxiliary definitions from ouroboros-consensus to cardano-ledger

### ISSUE THREAD

**Issue by edsko** [input-output-hk/cardano-ledger-byron#676]
Start with reviewing [https://github.com/input-output-hk/ouroboros-network/pull/1196/files](https://github.com/input-output-hk/ouroboros-network/pull/1196/files) and the Ouroboros.Consensus.Ledger.Byron.Aux module.

Firstly, the stuff in the Aux module can be grouped into three basic sections:

- The block validation interface
    - `validateBody`
    - `validateBlock`
    - `validateHeader`
    - `applyBoundary` - probably nothing here specifically worth testing
- The anachronistic protocol view interface
    - `applyScheduledDelegations`
- The mempool interface
    - `applyTxAux`
    - `applyCertificate`
    - `applyUpdateProposal`
    - `applyUpdateVote`

These sections represent the interface surface between the ledger and the consensus layer. Currently only the block validation interface is particularly specified. So we should also consider what properties hold of the others. We should also consider whether there are any other points of interface - for example, the consensus layer may wish to get certain "global constants" from the ledger - an obvious one is the map of epoch to epoch lengths.

A first task would be to move this module to `cardano-ledger`, make clear the distinct interface sections, and seek to include any further interface needed. We might want to split the interface into distinct modules to better represent their use - mempool, anachronism, block validation etc.

Where possible, the interface should define minimal logic, but there may be some sensible unit tests which could be written. In some cases, the existing conformance testing could be expanded to cover parts of the interface:

- `validateBlock`
- Parts of the mempool interface (e.g. we can check that transactions which get validated correctly as part of block `n` can be added to the mempool atop a chain stopping at block `n-1`.

We may wish to consider moving more of the anachronistic view to the ledger (and potentially specifying it in the formal spec). This would then allow more testing to cover that (which would be great, since it encodes some potentially subtle logic). The testing could be done along the lines of the time travel property as already encoded in the chain level spec.

**Comment by mrBliss** [comment]
@redxaxder Can you give a status update?

**Comment by edsko** [comment]
Might as well include https://github.com/input-output-hk/cardano-ledger/issues/685 here too (minor).
