### ISSUE TITLE
Design and implement blockchain-ledger interface

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#68]

**Comment by mdimjasevic** [comment]
Why are the design of the interface and the implementation of the interface put into a single task? Sure, they are related and it might take several iterations of going back and forth, but these are separate tasks.

**Comment by dnadales** [comment]
Actually, it is not a task, is an Epic. You can see this if you install the ZenHub extension. It is a pity this is not visible in plan Github (it used to be though, where ZenHub will put the Epic label automatically).

**Comment by ruhatch** [comment]
Converted this back to an issue as we are using epics to track the chunks from the planning diagram in the `fm-spec` repo.
