### ISSUE TITLE
Implement executable ledger spec

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#69]

**Comment by ruhatch** [comment]
This was not used and at the time of commenting the task is not complete.

**Comment by ruhatch** [comment]
Converting back to an issue, but it might not be broken down enough to be useful

**Comment by dnadales** [comment]
Yeah, we need to break this down or kill it with fire.

**Comment by commandodev** [comment]
@dnadales @ruhatch - Any progress on breaking this down or killing it?

**Comment by dnadales** [comment]
I'd say we can remove it.
