### ISSUE TITLE
Inconsistency in tx validity (fees) between old and new Byron ledger rules

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-ledger-byron#703]
On the testnet we have observed a transaction that the new relay nodes consider to be valid, but that the old cardano-sl nodes consider to be invalid due to not providing enough fees. This is a clear inconsistency: the old and new nodes should always agree that a tx is valid or invalid.

Here is a sample:

txid:
```
ee561326d28e151787bdda64114e8509fdb11197f3f0f4ecbf801bb24cf631f6
```
tx:
```
82839f8200d81858248258208beaf6a2b5172408f5b0d42237c208ab6a97405a114449d9bf2183f1eb9
97bae00ff9f8282d818584983581cff59e641d0ec2de249bc8fe142ea5f67d634f1ed13d44c28953c94
d0a201581e581c7655a411d01ff467a4e7c839df8e2442dc6bb94e9022a174dcbc758502451a4170cb1
7001a38a370e21a000f42408282d818582883581cf93cba7a732020e4dfb917533efec7c8ce630d99e7
4dd06726bab485a102451a4170cb17001a32f96f501a486280b6ffa0818200d8185885825840069dccf
653939e22e3c0a72eb64a54fb2c6346dec4574ac260c29e84e4914f1ce5e0a4702fcad806a6659f1887
4319048e47e19cf1d99b19ab3ea49a1d4ba9b95840dcd7dd8b7c7a8d315381e4baf5db0667db39faaa3
0bec7abd179dd66024696dd5c8e9387a278fecc985152706d41196b6108867104efb62fe9e66b2f16ce
5607
```
In the new node relay we see:
```
[e-a-1:cardano.node.Mempool:Debug:216] [2020-01-30 00:59:35.83 UTC] TraceMempoolAddTxs
 [tx: Tx ee561326d28e1517 with inputs [TxInUtxo 8beaf6a2 #0], outputs: [TxOut 1000000 lovelace ->
37btjrVyb4KGLZgVGTQdP8EX4tgnr6GGz7UFSM4TDBBghTtZsrZ5zvMREhdGC1yigiuiLo8hvZE9JHK3YZNnhETBMBBeWBWmssVduDFiciwjXArGFb,
TxOut 1214415030 lovelace -> 2cWKMJemoBamHfrnJceTyceGYiMn8Fx1dzE6j17RBttEcACMLWdXeH7ePKHgNic4ymXRh]
witnesses: [
    VKWitness: key = pub:069dccf6, key hash = 7bb4266a, sig = <signature>
],tx: Tx 1e396cd37a34b5cd with inputs [TxInUtxo 6c20d147 #0], outputs: [TxOut 1234567 lovelace ->
37btjrVyb4KBgwMPX9R2bRsgfr2b2KsnrJdKCrwM5EB6Dgh5idMZVwfzJ7JoqH9KwUJe1dYmbCqAQgvsC8amqtYCQhrSv1QiSWyw5UgoK86cu5PGq6,
TxOut 346952 lovelace -> 2cWKMJemoBaifvfaVWUsSZbHvAfgmoms2L6nWMsYoRQmckwoLQ2431wMVhSwUvHgEUYdh]
witnesses: [
    VKWitness: key = pub:8af26110, key hash = 77d612d5, sig = <signature>
]] (MempoolSize {msNumTxs = 2, msNumBytes = 672}) (Time 5432805.982104281s)
```
Yes, this is rather too verbose at the default level.

In the old node logs we see
```
[cardano-sl.node:Info:ThreadId 14944259] [2020-01-30 00:58:03.54 UTC] Transaction hasn't been
added to storage: ee561326d28e1517 , reason: transaction of size 334 B does not adhere to
policy(tx-size-linear): 155381 + 43.946*s; it has fee 168581 coin(s) but needs 170059 coin(s)
```

**Comment by dcoutts** [comment]
```82839f8200d81858248258208beaf6a2b5172408f5b0d42237c208ab6a97405a114449d9bf2183f1eb997bae00ff9f8282d818584983581cff59e641d0ec2de249bc8fe142ea5f67d634f1ed13d44c28953c94d0a201581e581c7655a411d01ff467a4e7c839df8e2442dc6bb94e9022a174dcbc758502451a4170cb17001a38a370e21a000f42408282d818582883581cf93cba7a732020e4dfb917533efec7c8ce630d99e74dd06726bab485a102451a4170cb17001a32f96f501a486280b6ffa0818200d8185885825840069dccf653939e22e3c0a72eb64a54fb2c6346dec4574ac260c29e84e4914f1ce5e0a4702fcad806a6659f18874319048e47e19cf1d99b19ab3ea49a1d4ba9b95840dcd7dd8b7c7a8d315381e4baf5db0667db39faaa30bec7abd179dd66024696dd5c8e9387a278fecc985152706d41196b6108867104efb62fe9e66b2f16ce5607```

Possibly I made a copy'n'paste error, but the above works fine in http://cbor.me/.

**Comment by nc6** [comment]
Is it possible to get the corresponding UTxO?

**Comment by nc6** [comment]
OK, in the old codebase, we calculate the minimum fee by looking at the size of the `TxAux` - e.g. the transaction with witnesses. This is done here:

```
verifyGState ::
       BlockVersionData
    -> EpochIndex
    -> TxAux
    -> VerifyTxUtxoRes
    -> Either ToilVerFailure ()
verifyGState bvd@BlockVersionData {..} curEpoch txAux vtur = do
    verifyBootEra bvd curEpoch txAux
    let txFeeMB = vturFee vtur
    let txSize = biSize txAux
    let limit = bvdMaxTxSize
    unless (isRedeemTx $ vturUndo vtur) $ whenJust txFeeMB $ \txFee ->
        verifyTxFeePolicy txFee bvdTxFeePolicy txSize
```

In the new codebase, however, we calculate the min fee based on the size of the transaction _without witnesses_:

```
validateTx
  :: MonadError TxValidationError m
  => Environment
  -> UTxO
  -> Annotated Tx ByteString
  -> m ()
validateTx env utxo (Annotated tx txBytes) = do
  
  [...]

  -- Calculate the minimum fee from the 'TxFeePolicy'
  minFee <- if isRedeemUTxO inputUTxO
    then pure $ mkKnownLovelace @0
    else calculateMinimumFee feePolicy

 where
  Environment { protocolMagic, protocolParameters, utxoConfiguration } = env

  feePolicy = ppTxFeePolicy protocolParameters

  txSize :: Natural
  txSize = fromIntegral $ BS.length txBytes

  calculateMinimumFee
    :: MonadError TxValidationError m => TxFeePolicy -> m Lovelace
  calculateMinimumFee = \case

    TxFeePolicyTxSizeLinear txSizeLinear ->
      calculateTxSizeLinear txSizeLinear txSize
        `wrapError` TxValidationLovelaceError "Minimum Fee"
```

So the computed minimum fee in the new codebase is going to be strictly less than that in the old codebase (and, perhaps more relevantly, no fee is charged for witnessing).

The lack of a charge for witnessing in the new code is _ambiguous_ in the specification, which merely defines an abstract size on the transaction (and allows a function from a transaction to its set of witnesses). The same is true of the Shelley spec.

**Comment by dcoutts** [comment]
This looks right. Lets see if we can validate that the old and new agree on the tx sizes.

**Comment by nc6** [comment]
They do (at least for the above quoted transaction)
