### ISSUE TITLE
Use current slot instead of latest block's slot when validating delegation certificates

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/cardano-ledger-byron#715]
## Background

This line is incorrect. The semantics of `cvsLastSlot` were recently refined such that it is now _always_ the slot of the latest block on the chain, which need not be the _current_ slot.

https://github.com/input-output-hk/cardano-ledger/blob/98048d95823b72e409b07481761b8a59c892c56c/cardano-ledger/src/Cardano/Chain/Byron/API.hs#L358

If I understand correctly, that code is only reached from a `applyMempoolPayload` call, and since that function is used within `ouroboros-consensus` to flush invalid transactions (including _expired_ delegation certificate transactions) from the mempool, it must actually use the _current_ slot.

## Proposed Solution

It suffices to simply add a `currentSlot` argument to `applyMempoolPayload`, which will be provided by the recently-added `tickedSlotNo` in the call in the `ouroboros-consensus` repo/library.

## Next Action
- [ ] Establish a local repro? (My current repro is a `test-consensus` failure; I'm not sure how to distill it down for inclusion into this repo).
- [x] PR here to fix: just add that `currentSlot` argument. (Edit: I've opened #716 for this.)
- [x] Update `ouroboros-consensus` (Should this step be a separate `ouroboros-consensus` ticket?)

**Comment by edsko** [comment]
Actually, _all_ uses of `cvsLastSlot` should be audited in the `API` module, now that `applyChainTick` does not modify this anymore.

**Comment by edsko** [comment]
https://github.com/input-output-hk/cardano-ledger/pull/716 addresses some uses of `cvsLastSlot`, but we should verify the other uses also before closing this ticket.

**Comment by nfrisby** [comment]
FYI: I see two direct uses of `cvsLastSlot` in `ouroboros-consensus`. (They seem accurate to me.)

**Comment by edsko** [comment]
I checked the other uses of `cvsLastSlot` in `.API`. I think they are all okay, except for

https://github.com/input-output-hk/cardano-ledger/blob/00d6cf3e82240f623863f4aec3aabb56f0c9ea5f/cardano-ledger/src/Cardano/Chain/Byron/API.hs#L370

which suffers from the same problem as the delegation environment.
