### ISSUE TITLE
Mismatch between formal spec and implementation

### ISSUE THREAD

**Issue by xxsanzxx** [input-output-hk/cardano-ledger-byron#718]
There is a mismatch between the formal specs and the code ([link](https://github.com/input-output-hk/cardano-ledger/blob/master/cardano-ledger/src/Cardano/Chain/Update/Validation/Registration.hs#L378)) when checking the maximum block size for an update proposal registration.

The formal specs state that “maximum transaction size must be smaller than the maximum block size (this requirement is crucial for having every transaction fitting in a block)” whilst the code checks that it is smaller or equal.

**Comment by nc6** [comment]
The critical check here is that both spec and code are in alignment with the old codebase - thus, assigning this as high priority since it's potentially an incompatibility.

**Comment by nc6** [comment]
OK, so this check doesn't exist in the old codebase at all. But it's also a bit spurious - putting the transaction limit anywhere near the block size makes for a fairly useless chain.

Formal and exec spec agree, so will change the implementation for simplicity.
