### ISSUE TITLE
Check compatibility of blockchain rules against standard notation doc

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#72]
The blockchain rules should adhere to the notation specified in the [standard notation document](https://github.com/input-output-hk/cardano-chain/tree/nc/semantics-spec).

This task simply involves going through the blockchain spec and checking compatibility with the aforementioned document.

**Comment by mdimjasevic** [comment]
Today I compared the blockchain layer specification against Nicholas' document and there should be no discrepancies as of PR #65.
