### ISSUE TITLE
registeredSoftwareUpdatesProposals is supposed to be preserved

### ISSUE THREAD

**Issue by ishaq** [input-output-hk/cardano-ledger-byron#725]
## Background
During audit, we noticed that https://github.com/input-output-hk/cardano-ledger/blob/bccf097bc589d082600132b63e9e787071568e12/cardano-ledger/src/Cardano/Chain/Update/Validation/Interface.hs#L497 sets `registeredSoftwareUpdateProposals` to `M.empty`.  According to the spec (Ledger rule 49, Fig. 45), it should be preserved.

**Comment by nc6** [comment]
Giving this high priority; discrepancy needs to be at least investigated.

**Comment by nc6** [comment]
Addressed through https://github.com/input-output-hk/cardano-ledger-specs/pull/1279 - we bring the formal spec in line with the exec spec and the implementation.
