### ISSUE TITLE
Prevent replay attacks with votes

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#739]
https://input-output-rnd.slack.com/archives/CCRB7BU8Y/p1583657858319300

Currently we do not check that votes are not replayed. We should therefore:
1. Update the spec (in the ADDVOTE rule) to prevent additional votes when `vts_pid` is already in `vts`)
2. Make the corresponding change in exec spec and implementation.
3. Verify that we can validate the existing mainnet chain (e.g. that it does not contain duplicate votes)

**Comment by dcoutts** [comment]
For the curious reading this, it is worth noting that it is only a problem that affects the original Byron ledger design, that we have to remain compatible with until the Shelley hard fork. The Shelley ledger has a comprehensive replay attack prevention mechanism, using the UTxO. In Shelley everything is a transaction, and all transactions must consume at least one UTxO entry. Certificates, update proposals, votes etc are all embedded within transactions.

**Comment by nc6** [comment]
PRs open for both the specs and ledger

**Comment by dcoutts** [comment]
PRs merged for both executable specs and the implementation.
