### ISSUE TITLE
Write generators that generate blockchains according to the OBFT protocol

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-byron#74]
The blockchain operational rules should be weaker than the Ourobouros BFT rules, so that the current Cardano implementation and the OBFT one can be validate by these.

However, we should write generators that generate OBFT compatible chains (chains generated according to the OBFT rules), and write `QuickCheck` (or `hedgehog`) properties stating that the generated chains are compatible with the OBFT chains.

We do not need in principle rules for the OBFT generators, but they might be nice to have.

**Comment by ruhatch** [comment]
This issue is a bit too broad, so I'm going to close it and I'll open a couple of new ones next week
