### ISSUE TITLE
Audit replay protection in Byron era delegation certs

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger-byron#741]
Check that delegation certificates have suitable replay protection.

**Comment by dcoutts** [comment]
For the curious reading this, it is worth noting that this worry does not affect Shelley. The Shelley ledger has a comprehensive replay attack prevention mechanism, using the UTxO. In Shelley everything is a transaction, and all transactions must consume at least one UTxO entry. Certificates, update proposals, votes etc are all embedded within transactions.

**Comment by kevinhammond** [comment]
If there is no protection then we will need to implement something presumably?

**Comment by kevinhammond** [comment]
Nick, please raise it and agree who's going to work on it

**Comment by nc6** [comment]
@kevinhammond I'm working through high priority byron tickets. This is on my list. I've done an initial audit, so this is just a more in depth one to check there aren't any subtle vectors

**Comment by nc6** [comment]
Have reviewed the spec and am confident there is no replay attack using delegation certs. This is crucially ensured by three properties:

- We only allow scheduling delegation for the current or next epoch.
- We do not allow duplicate (genesis key, epoch) pairs
- We only remove (genesis key, epoch) pairs for previous epochs
