### ISSUE TITLE
Address any technical-debt imported from `cardano-sl`

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#88]
Starting a fresh implementation is our opportunity to avoid any 'technical debt' we might have accrued in `cardano-sl`. A large chunk of code was imported from `cardano-sl`, so this epic aims to track and deal with any debt that may have been brought over.

**Comment by dnadales** [comment]
Any ideas on how we're going to track our work on technical debt? As far as I know "technical-debt-Friday" is just an implicit convention that we have :D
